In [1]:
import pandas as pd
import numpy as np

groupby() function is that it takes some dataframe, splits it into chunks based on some key values, applies computation on those chunks, then combines the results back together into another dataframe. In pandas this is refered to as the split-apply-combine pattern.

## Splitting

In [2]:
df = pd.read_csv('census.csv')
df = df[df['SUMLEV']==50]

In [3]:
df.head(10)

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
5,50,3,6,1,9,Alabama,Blount County,57322,57322,57373,...,1.807375,-1.177622,-1.748766,-2.062535,-1.369970,1.859511,-0.848580,-1.402476,-1.577232,-0.884411
6,50,3,6,1,11,Alabama,Bullock County,10914,10915,10887,...,-30.953709,-5.180127,-1.130263,14.354290,-16.167247,-29.001673,-2.825524,1.507017,17.243790,-13.193961
7,50,3,6,1,13,Alabama,Butler County,20947,20946,20944,...,-14.032727,-11.684234,-5.655413,1.085428,-6.529805,-13.936612,-11.586865,-5.557058,1.184103,-6.430868
8,50,3,6,1,15,Alabama,Calhoun County,118572,118586,118437,...,-6.155670,-4.611706,-5.524649,-4.463211,-3.376322,-5.791579,-4.092677,-5.062836,-3.912834,-2.806406
9,50,3,6,1,17,Alabama,Chambers County,34215,34170,34098,...,-2.731639,3.849092,2.872721,-2.287222,1.349468,-1.821092,4.701181,3.781439,-1.290228,2.346901
10,50,3,6,1,19,Alabama,Cherokee County,25989,25986,25976,...,6.339327,1.113180,5.488706,-0.076806,-3.239866,6.416167,1.420264,5.757384,0.230419,-2.931307

In [4]:
# Let's get a list of the unique states, then we can iterate over all the states and for each state 
# we reduce the data frame and calculate the average.

In [5]:
%%timeit -n 3
for state in df['STNAME'].unique():
    avg = np.average(df.where(df['STNAME']==state).dropna()['CENSUS2010POP'])
    print(f'The average population of {state} is {avg}')

The average population of Alabama is 71339.34328358209
The average population of Alaska is 24490.724137931036
The average population of Arizona is 426134.4666666667
The average population of Arkansas is 38878.90666666667
The average population of California is 642309.5862068966
The average population of Colorado is 78581.1875
The average population of Connecticut is 446762.125
The average population of Delaware is 299311.3333333333
The average population of District of Columbia is 601723.0
The average population of Florida is 280616.5671641791
The average population of Georgia is 60928.63522012578
The average population of Hawaii is 272060.2
The average population of Idaho is 35626.86363636364
The average population of Illinois is 125790.50980392157
The average population of Indiana is 70476.10869565218
The average population of Iowa is 30771.262626262625
The average population of Kansas is 27172.55238095238
The average population of Kentucky is 36161.39166666667
The average population of Louisiana is 70833.9375
The average population of Maine is 83022.5625
The average population of Maryland is 240564.66666666666
The average population of Massachusetts is 467687.78571428574
The average population of Michigan is 119080.0
The average population of Minnesota is 60964.65517241379
The average population of Mississippi is 36186.54878048781
The average population of Missouri is 52077.62608695652
The average population of Montana is 17668.125
The average population of Nebraska is 19638.075268817203
The average population of Nevada is 158855.9411764706
The average population of New Hampshire is 131647.0
The average population of New Jersey is 418661.61904761905
The average population of New Mexico is 62399.36363636364
The average population of New York is 312550.03225806454
The average population of North Carolina is 95354.83
The average population of North Dakota is 12690.396226415094
The average population of Ohio is 131096.63636363635
The average population of Oklahoma is 48718.844155844155
The average population of Oregon is 106418.72222222222
The average population of Pennsylvania is 189587.74626865672
The average population of Rhode Island is 210513.4
The average population of South Carolina is 100551.39130434782
The average population of South Dakota is 12336.060606060606
The average population of Tennessee is 66801.1052631579
The average population of Texas is 98998.27165354331
The average population of Utah is 95306.37931034483
The average population of Vermont is 44695.78571428572
The average population of Virginia is 60111.29323308271
The average population of Washington is 172424.10256410256
The average population of West Virginia is 33690.8
The average population of Wisconsin is 78985.91666666667
The average population of Wyoming is 24505.478260869564
The average population of Alabama is 71339.34328358209
The average population of Alaska is 24490.724137931036
The average population of Arizona is 426134.4666666667
The average population of Arkansas is 38878.90666666667
The average population of California is 642309.5862068966
The average population of Colorado is 78581.1875
The average population of Connecticut is 446762.125
The average population of Delaware is 299311.3333333333
The average population of District of Columbia is 601723.0
The average population of Florida is 280616.5671641791
The average population of Georgia is 60928.63522012578
The average population of Hawaii is 272060.2
The average population of Idaho is 35626.86363636364
The average population of Illinois is 125790.50980392157
The average population of Indiana is 70476.10869565218
The average population of Iowa is 30771.262626262625
The average population of Kansas is 27172.55238095238
The average population of Kentucky is 36161.39166666667
The average population of Louisiana is 70833.9375
The average population of Maine is 83022.5625
The average population of Maryland is 240564.66666666666
The average population of Massachusetts is 467687.78571428574
The average population of Michigan is 119080.0
The average population of Minnesota is 60964.65517241379
The average population of Mississippi is 36186.54878048781
The average population of Missouri is 52077.62608695652
The average population of Montana is 17668.125
The average population of Nebraska is 19638.075268817203
The average population of Nevada is 158855.9411764706
The average population of New Hampshire is 131647.0
The average population of New Jersey is 418661.61904761905
The average population of New Mexico is 62399.36363636364
The average population of New York is 312550.03225806454
The average population of North Carolina is 95354.83
The average population of North Dakota is 12690.396226415094
The average population of Ohio is 131096.63636363635
The average population of Oklahoma is 48718.844155844155
The average population of Oregon is 106418.72222222222
The average population of Pennsylvania is 189587.74626865672
The average population of Rhode Island is 210513.4
The average population of South Carolina is 100551.39130434782
The average population of South Dakota is 12336.060606060606
The average population of Tennessee is 66801.1052631579
The average population of Texas is 98998.27165354331
The average population of Utah is 95306.37931034483
The average population of Vermont is 44695.78571428572
The average population of Virginia is 60111.29323308271
The average population of Washington is 172424.10256410256
The average population of West Virginia is 33690.8
The average population of Wisconsin is 78985.91666666667
The average population of Wyoming is 24505.478260869564
The average population of Alabama is 71339.34328358209
The average population of Alaska is 24490.724137931036
The average population of Arizona is 426134.4666666667
The average population of Arkansas is 38878.90666666667
The average population of California is 642309.5862068966
The average population of Colorado is 78581.1875
The average population of Connecticut is 446762.125
The average population of Delaware is 299311.3333333333
The average population of District of Columbia is 601723.0
The average population of Florida is 280616.5671641791
The average population of Georgia is 60928.63522012578
The average population of Hawaii is 272060.2
The average population of Idaho is 35626.86363636364
The average population of Illinois is 125790.50980392157
The average population of Indiana is 70476.10869565218
The average population of Iowa is 30771.262626262625
The average population of Kansas is 27172.55238095238
The average population of Kentucky is 36161.39166666667
The average population of Louisiana is 70833.9375
The average population of Maine is 83022.5625
The average population of Maryland is 240564.66666666666
The average population of Massachusetts is 467687.78571428574
The average population of Michigan is 119080.0
The average population of Minnesota is 60964.65517241379
The average population of Mississippi is 36186.54878048781
The average population of Missouri is 52077.62608695652
The average population of Montana is 17668.125
The average population of Nebraska is 19638.075268817203
The average population of Nevada is 158855.9411764706
The average population of New Hampshire is 131647.0
The average population of New Jersey is 418661.61904761905
The average population of New Mexico is 62399.36363636364
The average population of New York is 312550.03225806454
The average population of North Carolina is 95354.83
The average population of North Dakota is 12690.396226415094
The average population of Ohio is 131096.63636363635
The average population of Oklahoma is 48718.844155844155
The average population of Oregon is 106418.72222222222
The average population of Pennsylvania is 189587.74626865672
The average population of Rhode Island is 210513.4
The average population of South Carolina is 100551.39130434782
The average population of South Dakota is 12336.060606060606
The average population of Tennessee is 66801.1052631579
The average population of Texas is 98998.27165354331
The average population of Utah is 95306.37931034483
The average population of Vermont is 44695.78571428572
The average population of Virginia is 60111.29323308271
The average population of Washington is 172424.10256410256
The average population of West Virginia is 33690.8
The average population of Wisconsin is 78985.91666666667
The average population of Wyoming is 24505.478260869564

The average population of Alabama is 71339.34328358209
The average population of Alaska is 24490.724137931036
The average population of Arizona is 426134.4666666667
The average population of Arkansas is 38878.90666666667
The average population of California is 642309.5862068966
The average population of Colorado is 78581.1875
The average population of Connecticut is 446762.125
The average population of Delaware is 299311.3333333333
The average population of District of Columbia is 601723.0
The average population of Florida is 280616.5671641791
The average population of Georgia is 60928.63522012578
The average population of Hawaii is 272060.2
The average population of Idaho is 35626.86363636364
The average population of Illinois is 125790.50980392157
The average population of Indiana is 70476.10869565218
The average population of Iowa is 30771.262626262625
The average population of Kansas is 27172.55238095238
The average population of Kentucky is 36161.39166666667
The average population of Louisiana is 70833.9375
The average population of Maine is 83022.5625
The average population of Maryland is 240564.66666666666
The average population of Massachusetts is 467687.78571428574
The average population of Michigan is 119080.0
The average population of Minnesota is 60964.65517241379
The average population of Mississippi is 36186.54878048781
The average population of Missouri is 52077.62608695652
The average population of Montana is 17668.125
The average population of Nebraska is 19638.075268817203
The average population of Nevada is 158855.9411764706
The average population of New Hampshire is 131647.0
The average population of New Jersey is 418661.61904761905
The average population of New Mexico is 62399.36363636364
The average population of New York is 312550.03225806454
The average population of North Carolina is 95354.83
The average population of North Dakota is 12690.396226415094
The average population of Ohio is 131096.63636363635
The average population of Oklahoma is 48718.844155844155
The average population of Oregon is 106418.72222222222
The average population of Pennsylvania is 189587.74626865672
The average population of Rhode Island is 210513.4
The average population of South Carolina is 100551.39130434782
The average population of South Dakota is 12336.060606060606
The average population of Tennessee is 66801.1052631579
The average population of Texas is 98998.27165354331
The average population of Utah is 95306.37931034483
The average population of Vermont is 44695.78571428572
The average population of Virginia is 60111.29323308271
The average population of Washington is 172424.10256410256
The average population of West Virginia is 33690.8
The average population of Wisconsin is 78985.91666666667
The average population of Wyoming is 24505.478260869564
The average population of Alabama is 71339.34328358209
The average population of Alaska is 24490.724137931036
The average population of Arizona is 426134.4666666667
The average population of Arkansas is 38878.90666666667
The average population of California is 642309.5862068966
The average population of Colorado is 78581.1875
The average population of Connecticut is 446762.125
The average population of Delaware is 299311.3333333333
The average population of District of Columbia is 601723.0
The average population of Florida is 280616.5671641791
The average population of Georgia is 60928.63522012578
The average population of Hawaii is 272060.2
The average population of Idaho is 35626.86363636364
The average population of Illinois is 125790.50980392157
The average population of Indiana is 70476.10869565218
The average population of Iowa is 30771.262626262625
The average population of Kansas is 27172.55238095238
The average population of Kentucky is 36161.39166666667
The average population of Louisiana is 70833.9375
The average population of Maine is 83022.5625
The average population of Maryland is 240564.66666666666
The average population of Massachusetts is 467687.78571428574
The average population of Michigan is 119080.0
The average population of Minnesota is 60964.65517241379
The average population of Mississippi is 36186.54878048781
The average population of Missouri is 52077.62608695652
The average population of Montana is 17668.125
The average population of Nebraska is 19638.075268817203
The average population of Nevada is 158855.9411764706
The average population of New Hampshire is 131647.0
The average population of New Jersey is 418661.61904761905
The average population of New Mexico is 62399.36363636364
The average population of New York is 312550.03225806454
The average population of North Carolina is 95354.83
The average population of North Dakota is 12690.396226415094
The average population of Ohio is 131096.63636363635
The average population of Oklahoma is 48718.844155844155
The average population of Oregon is 106418.72222222222
The average population of Pennsylvania is 189587.74626865672
The average population of Rhode Island is 210513.4
The average population of South Carolina is 100551.39130434782
The average population of South Dakota is 12336.060606060606
The average population of Tennessee is 66801.1052631579
The average population of Texas is 98998.27165354331
The average population of Utah is 95306.37931034483
The average population of Vermont is 44695.78571428572
The average population of Virginia is 60111.29323308271
The average population of Washington is 172424.10256410256
The average population of West Virginia is 33690.8
The average population of Wisconsin is 78985.91666666667
The average population of Wyoming is 24505.478260869564
The average population of Alabama is 71339.34328358209
The average population of Alaska is 24490.724137931036
The average population of Arizona is 426134.4666666667
The average population of Arkansas is 38878.90666666667
The average population of California is 642309.5862068966
The average population of Colorado is 78581.1875
The average population of Connecticut is 446762.125
The average population of Delaware is 299311.3333333333
The average population of District of Columbia is 601723.0
The average population of Florida is 280616.5671641791
The average population of Georgia is 60928.63522012578
The average population of Hawaii is 272060.2
The average population of Idaho is 35626.86363636364
The average population of Illinois is 125790.50980392157
The average population of Indiana is 70476.10869565218
The average population of Iowa is 30771.262626262625
The average population of Kansas is 27172.55238095238
The average population of Kentucky is 36161.39166666667
The average population of Louisiana is 70833.9375
The average population of Maine is 83022.5625
The average population of Maryland is 240564.66666666666
The average population of Massachusetts is 467687.78571428574
The average population of Michigan is 119080.0
The average population of Minnesota is 60964.65517241379
The average population of Mississippi is 36186.54878048781
The average population of Missouri is 52077.62608695652
The average population of Montana is 17668.125
The average population of Nebraska is 19638.075268817203
The average population of Nevada is 158855.9411764706
The average population of New Hampshire is 131647.0
The average population of New Jersey is 418661.61904761905
The average population of New Mexico is 62399.36363636364
The average population of New York is 312550.03225806454
The average population of North Carolina is 95354.83
The average population of North Dakota is 12690.396226415094
The average population of Ohio is 131096.63636363635
The average population of Oklahoma is 48718.844155844155
The average population of Oregon is 106418.72222222222
The average population of Pennsylvania is 189587.74626865672
The average population of Rhode Island is 210513.4
The average population of South Carolina is 100551.39130434782
The average population of South Dakota is 12336.060606060606
The average population of Tennessee is 66801.1052631579
The average population of Texas is 98998.27165354331
The average population of Utah is 95306.37931034483
The average population of Vermont is 44695.78571428572
The average population of Virginia is 60111.29323308271
The average population of Washington is 172424.10256410256

The average population of West Virginia is 33690.8
The average population of Wisconsin is 78985.91666666667
The average population of Wyoming is 24505.478260869564
The average population of Alabama is 71339.34328358209
The average population of Alaska is 24490.724137931036
The average population of Arizona is 426134.4666666667
The average population of Arkansas is 38878.90666666667
The average population of California is 642309.5862068966
The average population of Colorado is 78581.1875
The average population of Connecticut is 446762.125
The average population of Delaware is 299311.3333333333
The average population of District of Columbia is 601723.0
The average population of Florida is 280616.5671641791
The average population of Georgia is 60928.63522012578
The average population of Hawaii is 272060.2
The average population of Idaho is 35626.86363636364
The average population of Illinois is 125790.50980392157
The average population of Indiana is 70476.10869565218
The average population of Iowa is 30771.262626262625
The average population of Kansas is 27172.55238095238
The average population of Kentucky is 36161.39166666667
The average population of Louisiana is 70833.9375
The average population of Maine is 83022.5625
The average population of Maryland is 240564.66666666666
The average population of Massachusetts is 467687.78571428574
The average population of Michigan is 119080.0
The average population of Minnesota is 60964.65517241379
The average population of Mississippi is 36186.54878048781
The average population of Missouri is 52077.62608695652
The average population of Montana is 17668.125
The average population of Nebraska is 19638.075268817203
The average population of Nevada is 158855.9411764706
The average population of New Hampshire is 131647.0
The average population of New Jersey is 418661.61904761905
The average population of New Mexico is 62399.36363636364
The average population of New York is 312550.03225806454
The average population of North Carolina is 95354.83
The average population of North Dakota is 12690.396226415094
The average population of Ohio is 131096.63636363635
The average population of Oklahoma is 48718.844155844155
The average population of Oregon is 106418.72222222222
The average population of Pennsylvania is 189587.74626865672
The average population of Rhode Island is 210513.4
The average population of South Carolina is 100551.39130434782
The average population of South Dakota is 12336.060606060606
The average population of Tennessee is 66801.1052631579
The average population of Texas is 98998.27165354331
The average population of Utah is 95306.37931034483
The average population of Vermont is 44695.78571428572
The average population of Virginia is 60111.29323308271
The average population of Washington is 172424.10256410256
The average population of West Virginia is 33690.8
The average population of Wisconsin is 78985.91666666667
The average population of Wyoming is 24505.478260869564
The average population of Alabama is 71339.34328358209
The average population of Alaska is 24490.724137931036
The average population of Arizona is 426134.4666666667
The average population of Arkansas is 38878.90666666667
The average population of California is 642309.5862068966
The average population of Colorado is 78581.1875
The average population of Connecticut is 446762.125
The average population of Delaware is 299311.3333333333
The average population of District of Columbia is 601723.0
The average population of Florida is 280616.5671641791
The average population of Georgia is 60928.63522012578
The average population of Hawaii is 272060.2
The average population of Idaho is 35626.86363636364
The average population of Illinois is 125790.50980392157
The average population of Indiana is 70476.10869565218
The average population of Iowa is 30771.262626262625
The average population of Kansas is 27172.55238095238
The average population of Kentucky is 36161.39166666667
The average population of Louisiana is 70833.9375
The average population of Maine is 83022.5625
The average population of Maryland is 240564.66666666666
The average population of Massachusetts is 467687.78571428574
The average population of Michigan is 119080.0
The average population of Minnesota is 60964.65517241379
The average population of Mississippi is 36186.54878048781
The average population of Missouri is 52077.62608695652
The average population of Montana is 17668.125
The average population of Nebraska is 19638.075268817203
The average population of Nevada is 158855.9411764706
The average population of New Hampshire is 131647.0
The average population of New Jersey is 418661.61904761905
The average population of New Mexico is 62399.36363636364
The average population of New York is 312550.03225806454
The average population of North Carolina is 95354.83
The average population of North Dakota is 12690.396226415094
The average population of Ohio is 131096.63636363635
The average population of Oklahoma is 48718.844155844155
The average population of Oregon is 106418.72222222222
The average population of Pennsylvania is 189587.74626865672
The average population of Rhode Island is 210513.4
The average population of South Carolina is 100551.39130434782
The average population of South Dakota is 12336.060606060606
The average population of Tennessee is 66801.1052631579
The average population of Texas is 98998.27165354331
The average population of Utah is 95306.37931034483
The average population of Vermont is 44695.78571428572
The average population of Virginia is 60111.29323308271
The average population of Washington is 172424.10256410256
The average population of West Virginia is 33690.8
The average population of Wisconsin is 78985.91666666667
The average population of Wyoming is 24505.478260869564
The average population of Alabama is 71339.34328358209
The average population of Alaska is 24490.724137931036
The average population of Arizona is 426134.4666666667
The average population of Arkansas is 38878.90666666667
The average population of California is 642309.5862068966
The average population of Colorado is 78581.1875
The average population of Connecticut is 446762.125
The average population of Delaware is 299311.3333333333
The average population of District of Columbia is 601723.0
The average population of Florida is 280616.5671641791
The average population of Georgia is 60928.63522012578
The average population of Hawaii is 272060.2
The average population of Idaho is 35626.86363636364
The average population of Illinois is 125790.50980392157
The average population of Indiana is 70476.10869565218
The average population of Iowa is 30771.262626262625
The average population of Kansas is 27172.55238095238
The average population of Kentucky is 36161.39166666667
The average population of Louisiana is 70833.9375
The average population of Maine is 83022.5625
The average population of Maryland is 240564.66666666666
The average population of Massachusetts is 467687.78571428574
The average population of Michigan is 119080.0
The average population of Minnesota is 60964.65517241379
The average population of Mississippi is 36186.54878048781
The average population of Missouri is 52077.62608695652
The average population of Montana is 17668.125
The average population of Nebraska is 19638.075268817203
The average population of Nevada is 158855.9411764706
The average population of New Hampshire is 131647.0
The average population of New Jersey is 418661.61904761905
The average population of New Mexico is 62399.36363636364
The average population of New York is 312550.03225806454
The average population of North Carolina is 95354.83
The average population of North Dakota is 12690.396226415094
The average population of Ohio is 131096.63636363635
The average population of Oklahoma is 48718.844155844155
The average population of Oregon is 106418.72222222222
The average population of Pennsylvania is 189587.74626865672
The average population of Rhode Island is 210513.4
The average population of South Carolina is 100551.39130434782
The average population of South Dakota is 12336.060606060606
The average population of Tennessee is 66801.1052631579
The average population of Texas is 98998.27165354331
The average population of Utah is 95306.37931034483
The average population of Vermont is 44695.78571428572
The average population of Virginia is 60111.29323308271
The average population of Washington is 172424.10256410256

The average population of West Virginia is 33690.8
The average population of Wisconsin is 78985.91666666667
The average population of Wyoming is 24505.478260869564
The average population of Alabama is 71339.34328358209
The average population of Alaska is 24490.724137931036
The average population of Arizona is 426134.4666666667
The average population of Arkansas is 38878.90666666667
The average population of California is 642309.5862068966
The average population of Colorado is 78581.1875
The average population of Connecticut is 446762.125
The average population of Delaware is 299311.3333333333
The average population of District of Columbia is 601723.0
The average population of Florida is 280616.5671641791
The average population of Georgia is 60928.63522012578
The average population of Hawaii is 272060.2
The average population of Idaho is 35626.86363636364
The average population of Illinois is 125790.50980392157
The average population of Indiana is 70476.10869565218
The average population of Iowa is 30771.262626262625
The average population of Kansas is 27172.55238095238
The average population of Kentucky is 36161.39166666667
The average population of Louisiana is 70833.9375
The average population of Maine is 83022.5625
The average population of Maryland is 240564.66666666666
The average population of Massachusetts is 467687.78571428574
The average population of Michigan is 119080.0
The average population of Minnesota is 60964.65517241379
The average population of Mississippi is 36186.54878048781
The average population of Missouri is 52077.62608695652
The average population of Montana is 17668.125
The average population of Nebraska is 19638.075268817203
The average population of Nevada is 158855.9411764706
The average population of New Hampshire is 131647.0
The average population of New Jersey is 418661.61904761905
The average population of New Mexico is 62399.36363636364
The average population of New York is 312550.03225806454
The average population of North Carolina is 95354.83
The average population of North Dakota is 12690.396226415094
The average population of Ohio is 131096.63636363635
The average population of Oklahoma is 48718.844155844155
The average population of Oregon is 106418.72222222222
The average population of Pennsylvania is 189587.74626865672
The average population of Rhode Island is 210513.4
The average population of South Carolina is 100551.39130434782
The average population of South Dakota is 12336.060606060606
The average population of Tennessee is 66801.1052631579
The average population of Texas is 98998.27165354331
The average population of Utah is 95306.37931034483
The average population of Vermont is 44695.78571428572
The average population of Virginia is 60111.29323308271
The average population of Washington is 172424.10256410256
The average population of West Virginia is 33690.8
The average population of Wisconsin is 78985.91666666667
The average population of Wyoming is 24505.478260869564
The average population of Alabama is 71339.34328358209
The average population of Alaska is 24490.724137931036
The average population of Arizona is 426134.4666666667
The average population of Arkansas is 38878.90666666667
The average population of California is 642309.5862068966
The average population of Colorado is 78581.1875
The average population of Connecticut is 446762.125
The average population of Delaware is 299311.3333333333
The average population of District of Columbia is 601723.0
The average population of Florida is 280616.5671641791
The average population of Georgia is 60928.63522012578
The average population of Hawaii is 272060.2
The average population of Idaho is 35626.86363636364
The average population of Illinois is 125790.50980392157
The average population of Indiana is 70476.10869565218
The average population of Iowa is 30771.262626262625
The average population of Kansas is 27172.55238095238
The average population of Kentucky is 36161.39166666667
The average population of Louisiana is 70833.9375
The average population of Maine is 83022.5625
The average population of Maryland is 240564.66666666666
The average population of Massachusetts is 467687.78571428574
The average population of Michigan is 119080.0
The average population of Minnesota is 60964.65517241379
The average population of Mississippi is 36186.54878048781
The average population of Missouri is 52077.62608695652
The average population of Montana is 17668.125
The average population of Nebraska is 19638.075268817203
The average population of Nevada is 158855.9411764706
The average population of New Hampshire is 131647.0
The average population of New Jersey is 418661.61904761905
The average population of New Mexico is 62399.36363636364
The average population of New York is 312550.03225806454
The average population of North Carolina is 95354.83
The average population of North Dakota is 12690.396226415094
The average population of Ohio is 131096.63636363635
The average population of Oklahoma is 48718.844155844155
The average population of Oregon is 106418.72222222222
The average population of Pennsylvania is 189587.74626865672
The average population of Rhode Island is 210513.4
The average population of South Carolina is 100551.39130434782
The average population of South Dakota is 12336.060606060606
The average population of Tennessee is 66801.1052631579
The average population of Texas is 98998.27165354331
The average population of Utah is 95306.37931034483
The average population of Vermont is 44695.78571428572
The average population of Virginia is 60111.29323308271
The average population of Washington is 172424.10256410256
The average population of West Virginia is 33690.8
The average population of Wisconsin is 78985.91666666667
The average population of Wyoming is 24505.478260869564
The average population of Alabama is 71339.34328358209
The average population of Alaska is 24490.724137931036
The average population of Arizona is 426134.4666666667
The average population of Arkansas is 38878.90666666667
The average population of California is 642309.5862068966
The average population of Colorado is 78581.1875
The average population of Connecticut is 446762.125
The average population of Delaware is 299311.3333333333
The average population of District of Columbia is 601723.0
The average population of Florida is 280616.5671641791
The average population of Georgia is 60928.63522012578
The average population of Hawaii is 272060.2
The average population of Idaho is 35626.86363636364
The average population of Illinois is 125790.50980392157
The average population of Indiana is 70476.10869565218
The average population of Iowa is 30771.262626262625
The average population of Kansas is 27172.55238095238
The average population of Kentucky is 36161.39166666667
The average population of Louisiana is 70833.9375
The average population of Maine is 83022.5625
The average population of Maryland is 240564.66666666666
The average population of Massachusetts is 467687.78571428574
The average population of Michigan is 119080.0
The average population of Minnesota is 60964.65517241379
The average population of Mississippi is 36186.54878048781
The average population of Missouri is 52077.62608695652
The average population of Montana is 17668.125
The average population of Nebraska is 19638.075268817203
The average population of Nevada is 158855.9411764706
The average population of New Hampshire is 131647.0
The average population of New Jersey is 418661.61904761905
The average population of New Mexico is 62399.36363636364
The average population of New York is 312550.03225806454
The average population of North Carolina is 95354.83
The average population of North Dakota is 12690.396226415094
The average population of Ohio is 131096.63636363635
The average population of Oklahoma is 48718.844155844155
The average population of Oregon is 106418.72222222222
The average population of Pennsylvania is 189587.74626865672
The average population of Rhode Island is 210513.4
The average population of South Carolina is 100551.39130434782
The average population of South Dakota is 12336.060606060606
The average population of Tennessee is 66801.1052631579
The average population of Texas is 98998.27165354331
The average population of Utah is 95306.37931034483
The average population of Vermont is 44695.78571428572

The average population of Virginia is 60111.29323308271
The average population of Washington is 172424.10256410256
The average population of West Virginia is 33690.8
The average population of Wisconsin is 78985.91666666667
The average population of Wyoming is 24505.478260869564
The average population of Alabama is 71339.34328358209
The average population of Alaska is 24490.724137931036
The average population of Arizona is 426134.4666666667
The average population of Arkansas is 38878.90666666667
The average population of California is 642309.5862068966
The average population of Colorado is 78581.1875
The average population of Connecticut is 446762.125
The average population of Delaware is 299311.3333333333
The average population of District of Columbia is 601723.0
The average population of Florida is 280616.5671641791
The average population of Georgia is 60928.63522012578
The average population of Hawaii is 272060.2
The average population of Idaho is 35626.86363636364
The average population of Illinois is 125790.50980392157
The average population of Indiana is 70476.10869565218
The average population of Iowa is 30771.262626262625
The average population of Kansas is 27172.55238095238
The average population of Kentucky is 36161.39166666667
The average population of Louisiana is 70833.9375
The average population of Maine is 83022.5625
The average population of Maryland is 240564.66666666666
The average population of Massachusetts is 467687.78571428574
The average population of Michigan is 119080.0
The average population of Minnesota is 60964.65517241379
The average population of Mississippi is 36186.54878048781
The average population of Missouri is 52077.62608695652
The average population of Montana is 17668.125
The average population of Nebraska is 19638.075268817203
The average population of Nevada is 158855.9411764706
The average population of New Hampshire is 131647.0
The average population of New Jersey is 418661.61904761905
The average population of New Mexico is 62399.36363636364
The average population of New York is 312550.03225806454
The average population of North Carolina is 95354.83
The average population of North Dakota is 12690.396226415094
The average population of Ohio is 131096.63636363635
The average population of Oklahoma is 48718.844155844155
The average population of Oregon is 106418.72222222222
The average population of Pennsylvania is 189587.74626865672
The average population of Rhode Island is 210513.4
The average population of South Carolina is 100551.39130434782
The average population of South Dakota is 12336.060606060606
The average population of Tennessee is 66801.1052631579
The average population of Texas is 98998.27165354331
The average population of Utah is 95306.37931034483
The average population of Vermont is 44695.78571428572
The average population of Virginia is 60111.29323308271
The average population of Washington is 172424.10256410256
The average population of West Virginia is 33690.8
The average population of Wisconsin is 78985.91666666667
The average population of Wyoming is 24505.478260869564
The average population of Alabama is 71339.34328358209
The average population of Alaska is 24490.724137931036
The average population of Arizona is 426134.4666666667
The average population of Arkansas is 38878.90666666667
The average population of California is 642309.5862068966
The average population of Colorado is 78581.1875
The average population of Connecticut is 446762.125
The average population of Delaware is 299311.3333333333
The average population of District of Columbia is 601723.0
The average population of Florida is 280616.5671641791
The average population of Georgia is 60928.63522012578
The average population of Hawaii is 272060.2
The average population of Idaho is 35626.86363636364
The average population of Illinois is 125790.50980392157
The average population of Indiana is 70476.10869565218
The average population of Iowa is 30771.262626262625
The average population of Kansas is 27172.55238095238
The average population of Kentucky is 36161.39166666667
The average population of Louisiana is 70833.9375
The average population of Maine is 83022.5625
The average population of Maryland is 240564.66666666666
The average population of Massachusetts is 467687.78571428574
The average population of Michigan is 119080.0
The average population of Minnesota is 60964.65517241379
The average population of Mississippi is 36186.54878048781
The average population of Missouri is 52077.62608695652
The average population of Montana is 17668.125
The average population of Nebraska is 19638.075268817203
The average population of Nevada is 158855.9411764706
The average population of New Hampshire is 131647.0
The average population of New Jersey is 418661.61904761905
The average population of New Mexico is 62399.36363636364
The average population of New York is 312550.03225806454
The average population of North Carolina is 95354.83
The average population of North Dakota is 12690.396226415094
The average population of Ohio is 131096.63636363635
The average population of Oklahoma is 48718.844155844155
The average population of Oregon is 106418.72222222222
The average population of Pennsylvania is 189587.74626865672
The average population of Rhode Island is 210513.4
The average population of South Carolina is 100551.39130434782
The average population of South Dakota is 12336.060606060606
The average population of Tennessee is 66801.1052631579
The average population of Texas is 98998.27165354331
The average population of Utah is 95306.37931034483
The average population of Vermont is 44695.78571428572
The average population of Virginia is 60111.29323308271
The average population of Washington is 172424.10256410256
The average population of West Virginia is 33690.8
The average population of Wisconsin is 78985.91666666667
The average population of Wyoming is 24505.478260869564
The average population of Alabama is 71339.34328358209
The average population of Alaska is 24490.724137931036
The average population of Arizona is 426134.4666666667
The average population of Arkansas is 38878.90666666667
The average population of California is 642309.5862068966
The average population of Colorado is 78581.1875
The average population of Connecticut is 446762.125
The average population of Delaware is 299311.3333333333
The average population of District of Columbia is 601723.0
The average population of Florida is 280616.5671641791
The average population of Georgia is 60928.63522012578
The average population of Hawaii is 272060.2
The average population of Idaho is 35626.86363636364
The average population of Illinois is 125790.50980392157
The average population of Indiana is 70476.10869565218
The average population of Iowa is 30771.262626262625
The average population of Kansas is 27172.55238095238
The average population of Kentucky is 36161.39166666667
The average population of Louisiana is 70833.9375
The average population of Maine is 83022.5625
The average population of Maryland is 240564.66666666666
The average population of Massachusetts is 467687.78571428574
The average population of Michigan is 119080.0
The average population of Minnesota is 60964.65517241379
The average population of Mississippi is 36186.54878048781
The average population of Missouri is 52077.62608695652
The average population of Montana is 17668.125
The average population of Nebraska is 19638.075268817203
The average population of Nevada is 158855.9411764706
The average population of New Hampshire is 131647.0
The average population of New Jersey is 418661.61904761905
The average population of New Mexico is 62399.36363636364
The average population of New York is 312550.03225806454
The average population of North Carolina is 95354.83
The average population of North Dakota is 12690.396226415094
The average population of Ohio is 131096.63636363635
The average population of Oklahoma is 48718.844155844155
The average population of Oregon is 106418.72222222222
The average population of Pennsylvania is 189587.74626865672
The average population of Rhode Island is 210513.4
The average population of South Carolina is 100551.39130434782
The average population of South Dakota is 12336.060606060606

The average population of Tennessee is 66801.1052631579
The average population of Texas is 98998.27165354331
The average population of Utah is 95306.37931034483
The average population of Vermont is 44695.78571428572
The average population of Virginia is 60111.29323308271
The average population of Washington is 172424.10256410256
The average population of West Virginia is 33690.8
The average population of Wisconsin is 78985.91666666667
The average population of Wyoming is 24505.478260869564
The average population of Alabama is 71339.34328358209
The average population of Alaska is 24490.724137931036
The average population of Arizona is 426134.4666666667
The average population of Arkansas is 38878.90666666667
The average population of California is 642309.5862068966
The average population of Colorado is 78581.1875
The average population of Connecticut is 446762.125
The average population of Delaware is 299311.3333333333
The average population of District of Columbia is 601723.0
The average population of Florida is 280616.5671641791
The average population of Georgia is 60928.63522012578
The average population of Hawaii is 272060.2
The average population of Idaho is 35626.86363636364
The average population of Illinois is 125790.50980392157
The average population of Indiana is 70476.10869565218
The average population of Iowa is 30771.262626262625
The average population of Kansas is 27172.55238095238
The average population of Kentucky is 36161.39166666667
The average population of Louisiana is 70833.9375
The average population of Maine is 83022.5625
The average population of Maryland is 240564.66666666666
The average population of Massachusetts is 467687.78571428574
The average population of Michigan is 119080.0
The average population of Minnesota is 60964.65517241379
The average population of Mississippi is 36186.54878048781
The average population of Missouri is 52077.62608695652
The average population of Montana is 17668.125
The average population of Nebraska is 19638.075268817203
The average population of Nevada is 158855.9411764706
The average population of New Hampshire is 131647.0
The average population of New Jersey is 418661.61904761905
The average population of New Mexico is 62399.36363636364
The average population of New York is 312550.03225806454
The average population of North Carolina is 95354.83
The average population of North Dakota is 12690.396226415094
The average population of Ohio is 131096.63636363635
The average population of Oklahoma is 48718.844155844155
The average population of Oregon is 106418.72222222222
The average population of Pennsylvania is 189587.74626865672
The average population of Rhode Island is 210513.4
The average population of South Carolina is 100551.39130434782
The average population of South Dakota is 12336.060606060606
The average population of Tennessee is 66801.1052631579
The average population of Texas is 98998.27165354331
The average population of Utah is 95306.37931034483
The average population of Vermont is 44695.78571428572
The average population of Virginia is 60111.29323308271
The average population of Washington is 172424.10256410256
The average population of West Virginia is 33690.8
The average population of Wisconsin is 78985.91666666667
The average population of Wyoming is 24505.478260869564
The average population of Alabama is 71339.34328358209
The average population of Alaska is 24490.724137931036
The average population of Arizona is 426134.4666666667
The average population of Arkansas is 38878.90666666667
The average population of California is 642309.5862068966
The average population of Colorado is 78581.1875
The average population of Connecticut is 446762.125
The average population of Delaware is 299311.3333333333
The average population of District of Columbia is 601723.0
The average population of Florida is 280616.5671641791
The average population of Georgia is 60928.63522012578
The average population of Hawaii is 272060.2
The average population of Idaho is 35626.86363636364
The average population of Illinois is 125790.50980392157
The average population of Indiana is 70476.10869565218
The average population of Iowa is 30771.262626262625
The average population of Kansas is 27172.55238095238
The average population of Kentucky is 36161.39166666667
The average population of Louisiana is 70833.9375
The average population of Maine is 83022.5625
The average population of Maryland is 240564.66666666666
The average population of Massachusetts is 467687.78571428574
The average population of Michigan is 119080.0
The average population of Minnesota is 60964.65517241379
The average population of Mississippi is 36186.54878048781
The average population of Missouri is 52077.62608695652
The average population of Montana is 17668.125
The average population of Nebraska is 19638.075268817203
The average population of Nevada is 158855.9411764706
The average population of New Hampshire is 131647.0
The average population of New Jersey is 418661.61904761905
The average population of New Mexico is 62399.36363636364
The average population of New York is 312550.03225806454
The average population of North Carolina is 95354.83
The average population of North Dakota is 12690.396226415094
The average population of Ohio is 131096.63636363635
The average population of Oklahoma is 48718.844155844155
The average population of Oregon is 106418.72222222222
The average population of Pennsylvania is 189587.74626865672
The average population of Rhode Island is 210513.4
The average population of South Carolina is 100551.39130434782
The average population of South Dakota is 12336.060606060606
The average population of Tennessee is 66801.1052631579
The average population of Texas is 98998.27165354331
The average population of Utah is 95306.37931034483
The average population of Vermont is 44695.78571428572
The average population of Virginia is 60111.29323308271
The average population of Washington is 172424.10256410256
The average population of West Virginia is 33690.8
The average population of Wisconsin is 78985.91666666667
The average population of Wyoming is 24505.478260869564
The average population of Alabama is 71339.34328358209
The average population of Alaska is 24490.724137931036
The average population of Arizona is 426134.4666666667
The average population of Arkansas is 38878.90666666667
The average population of California is 642309.5862068966
The average population of Colorado is 78581.1875
The average population of Connecticut is 446762.125
The average population of Delaware is 299311.3333333333
The average population of District of Columbia is 601723.0
The average population of Florida is 280616.5671641791
The average population of Georgia is 60928.63522012578
The average population of Hawaii is 272060.2
The average population of Idaho is 35626.86363636364
The average population of Illinois is 125790.50980392157
The average population of Indiana is 70476.10869565218
The average population of Iowa is 30771.262626262625
The average population of Kansas is 27172.55238095238
The average population of Kentucky is 36161.39166666667
The average population of Louisiana is 70833.9375
The average population of Maine is 83022.5625
The average population of Maryland is 240564.66666666666
The average population of Massachusetts is 467687.78571428574
The average population of Michigan is 119080.0
The average population of Minnesota is 60964.65517241379
The average population of Mississippi is 36186.54878048781
The average population of Missouri is 52077.62608695652
The average population of Montana is 17668.125
The average population of Nebraska is 19638.075268817203
The average population of Nevada is 158855.9411764706
The average population of New Hampshire is 131647.0
The average population of New Jersey is 418661.61904761905
The average population of New Mexico is 62399.36363636364
The average population of New York is 312550.03225806454
The average population of North Carolina is 95354.83
The average population of North Dakota is 12690.396226415094
The average population of Ohio is 131096.63636363635
The average population of Oklahoma is 48718.844155844155
The average population of Oregon is 106418.72222222222
The average population of Pennsylvania is 189587.74626865672
The average population of Rhode Island is 210513.4

The average population of South Carolina is 100551.39130434782
The average population of South Dakota is 12336.060606060606
The average population of Tennessee is 66801.1052631579
The average population of Texas is 98998.27165354331
The average population of Utah is 95306.37931034483
The average population of Vermont is 44695.78571428572
The average population of Virginia is 60111.29323308271
The average population of Washington is 172424.10256410256
The average population of West Virginia is 33690.8
The average population of Wisconsin is 78985.91666666667
The average population of Wyoming is 24505.478260869564
The average population of Alabama is 71339.34328358209
The average population of Alaska is 24490.724137931036
The average population of Arizona is 426134.4666666667
The average population of Arkansas is 38878.90666666667
The average population of California is 642309.5862068966
The average population of Colorado is 78581.1875
The average population of Connecticut is 446762.125
The average population of Delaware is 299311.3333333333
The average population of District of Columbia is 601723.0
The average population of Florida is 280616.5671641791
The average population of Georgia is 60928.63522012578
The average population of Hawaii is 272060.2
The average population of Idaho is 35626.86363636364
The average population of Illinois is 125790.50980392157
The average population of Indiana is 70476.10869565218
The average population of Iowa is 30771.262626262625
The average population of Kansas is 27172.55238095238
The average population of Kentucky is 36161.39166666667
The average population of Louisiana is 70833.9375
The average population of Maine is 83022.5625
The average population of Maryland is 240564.66666666666
The average population of Massachusetts is 467687.78571428574
The average population of Michigan is 119080.0
The average population of Minnesota is 60964.65517241379
The average population of Mississippi is 36186.54878048781
The average population of Missouri is 52077.62608695652
The average population of Montana is 17668.125
The average population of Nebraska is 19638.075268817203
The average population of Nevada is 158855.9411764706
The average population of New Hampshire is 131647.0
The average population of New Jersey is 418661.61904761905
The average population of New Mexico is 62399.36363636364
The average population of New York is 312550.03225806454
The average population of North Carolina is 95354.83
The average population of North Dakota is 12690.396226415094
The average population of Ohio is 131096.63636363635
The average population of Oklahoma is 48718.844155844155
The average population of Oregon is 106418.72222222222
The average population of Pennsylvania is 189587.74626865672
The average population of Rhode Island is 210513.4
The average population of South Carolina is 100551.39130434782
The average population of South Dakota is 12336.060606060606
The average population of Tennessee is 66801.1052631579
The average population of Texas is 98998.27165354331
The average population of Utah is 95306.37931034483
The average population of Vermont is 44695.78571428572
The average population of Virginia is 60111.29323308271
The average population of Washington is 172424.10256410256
The average population of West Virginia is 33690.8
The average population of Wisconsin is 78985.91666666667
The average population of Wyoming is 24505.478260869564
The average population of Alabama is 71339.34328358209
The average population of Alaska is 24490.724137931036
The average population of Arizona is 426134.4666666667
The average population of Arkansas is 38878.90666666667
The average population of California is 642309.5862068966
The average population of Colorado is 78581.1875
The average population of Connecticut is 446762.125
The average population of Delaware is 299311.3333333333
The average population of District of Columbia is 601723.0
The average population of Florida is 280616.5671641791
The average population of Georgia is 60928.63522012578
The average population of Hawaii is 272060.2
The average population of Idaho is 35626.86363636364
The average population of Illinois is 125790.50980392157
The average population of Indiana is 70476.10869565218
The average population of Iowa is 30771.262626262625
The average population of Kansas is 27172.55238095238
The average population of Kentucky is 36161.39166666667
The average population of Louisiana is 70833.9375
The average population of Maine is 83022.5625
The average population of Maryland is 240564.66666666666
The average population of Massachusetts is 467687.78571428574
The average population of Michigan is 119080.0
The average population of Minnesota is 60964.65517241379
The average population of Mississippi is 36186.54878048781
The average population of Missouri is 52077.62608695652
The average population of Montana is 17668.125
The average population of Nebraska is 19638.075268817203
The average population of Nevada is 158855.9411764706
The average population of New Hampshire is 131647.0
The average population of New Jersey is 418661.61904761905
The average population of New Mexico is 62399.36363636364
The average population of New York is 312550.03225806454
The average population of North Carolina is 95354.83
The average population of North Dakota is 12690.396226415094
The average population of Ohio is 131096.63636363635
The average population of Oklahoma is 48718.844155844155
The average population of Oregon is 106418.72222222222
The average population of Pennsylvania is 189587.74626865672
The average population of Rhode Island is 210513.4
The average population of South Carolina is 100551.39130434782
The average population of South Dakota is 12336.060606060606
The average population of Tennessee is 66801.1052631579
The average population of Texas is 98998.27165354331
The average population of Utah is 95306.37931034483
The average population of Vermont is 44695.78571428572
The average population of Virginia is 60111.29323308271
The average population of Washington is 172424.10256410256
The average population of West Virginia is 33690.8
The average population of Wisconsin is 78985.91666666667
The average population of Wyoming is 24505.478260869564
The average population of Alabama is 71339.34328358209
The average population of Alaska is 24490.724137931036
The average population of Arizona is 426134.4666666667
The average population of Arkansas is 38878.90666666667
The average population of California is 642309.5862068966
The average population of Colorado is 78581.1875
The average population of Connecticut is 446762.125
The average population of Delaware is 299311.3333333333
The average population of District of Columbia is 601723.0
The average population of Florida is 280616.5671641791
The average population of Georgia is 60928.63522012578
The average population of Hawaii is 272060.2
The average population of Idaho is 35626.86363636364
The average population of Illinois is 125790.50980392157
The average population of Indiana is 70476.10869565218
The average population of Iowa is 30771.262626262625
The average population of Kansas is 27172.55238095238
The average population of Kentucky is 36161.39166666667
The average population of Louisiana is 70833.9375
The average population of Maine is 83022.5625
The average population of Maryland is 240564.66666666666
The average population of Massachusetts is 467687.78571428574
The average population of Michigan is 119080.0
The average population of Minnesota is 60964.65517241379
The average population of Mississippi is 36186.54878048781
The average population of Missouri is 52077.62608695652
The average population of Montana is 17668.125
The average population of Nebraska is 19638.075268817203
The average population of Nevada is 158855.9411764706
The average population of New Hampshire is 131647.0
The average population of New Jersey is 418661.61904761905
The average population of New Mexico is 62399.36363636364
The average population of New York is 312550.03225806454
The average population of North Carolina is 95354.83
The average population of North Dakota is 12690.396226415094
The average population of Ohio is 131096.63636363635
The average population of Oklahoma is 48718.844155844155
The average population of Oregon is 106418.72222222222
The average population of Pennsylvania is 189587.74626865672
The average population of Rhode Island is 210513.4
The average population of South Carolina is 100551.39130434782

The average population of South Dakota is 12336.060606060606
The average population of Tennessee is 66801.1052631579
The average population of Texas is 98998.27165354331
The average population of Utah is 95306.37931034483
The average population of Vermont is 44695.78571428572
The average population of Virginia is 60111.29323308271
The average population of Washington is 172424.10256410256
The average population of West Virginia is 33690.8
The average population of Wisconsin is 78985.91666666667
The average population of Wyoming is 24505.478260869564
2.06 s ± 316 ms per loop (mean ± std. dev. of 7 runs, 3 loops each)

In [6]:
# Now let's try another approach using groupby()
# For this method, we start by telling pandas we're interested in grouping by state name, this is the "split"
# You'll notice there are two values we set here. groupby() returns a tuple, where the first value is the
    # value of the key we were trying to group by, in this case a specific state name, and the second one is
    # projected dataframe that was found for that group

In [7]:
%%timeit -n 3
for state, frame in df.groupby('STNAME'):
    avg = np.average(frame['CENSUS2010POP'])
    print(f'The average of {state} is {avg}')

The average of Alabama is 71339.34328358209
The average of Alaska is 24490.724137931036
The average of Arizona is 426134.4666666667
The average of Arkansas is 38878.90666666667
The average of California is 642309.5862068966
The average of Colorado is 78581.1875
The average of Connecticut is 446762.125
The average of Delaware is 299311.3333333333
The average of District of Columbia is 601723.0
The average of Florida is 280616.5671641791
The average of Georgia is 60928.63522012578
The average of Hawaii is 272060.2
The average of Idaho is 35626.86363636364
The average of Illinois is 125790.50980392157
The average of Indiana is 70476.10869565218
The average of Iowa is 30771.262626262625
The average of Kansas is 27172.55238095238
The average of Kentucky is 36161.39166666667
The average of Louisiana is 70833.9375
The average of Maine is 83022.5625
The average of Maryland is 240564.66666666666
The average of Massachusetts is 467687.78571428574
The average of Michigan is 119080.0
The average of Minnesota is 60964.65517241379
The average of Mississippi is 36186.54878048781
The average of Missouri is 52077.62608695652
The average of Montana is 17668.125
The average of Nebraska is 19638.075268817203
The average of Nevada is 158855.9411764706
The average of New Hampshire is 131647.0
The average of New Jersey is 418661.61904761905
The average of New Mexico is 62399.36363636364
The average of New York is 312550.03225806454
The average of North Carolina is 95354.83
The average of North Dakota is 12690.396226415094
The average of Ohio is 131096.63636363635
The average of Oklahoma is 48718.844155844155
The average of Oregon is 106418.72222222222
The average of Pennsylvania is 189587.74626865672
The average of Rhode Island is 210513.4
The average of South Carolina is 100551.39130434782
The average of South Dakota is 12336.060606060606
The average of Tennessee is 66801.1052631579
The average of Texas is 98998.27165354331
The average of Utah is 95306.37931034483
The average of Vermont is 44695.78571428572
The average of Virginia is 60111.29323308271
The average of Washington is 172424.10256410256
The average of West Virginia is 33690.8
The average of Wisconsin is 78985.91666666667
The average of Wyoming is 24505.478260869564
The average of Alabama is 71339.34328358209
The average of Alaska is 24490.724137931036
The average of Arizona is 426134.4666666667
The average of Arkansas is 38878.90666666667
The average of California is 642309.5862068966
The average of Colorado is 78581.1875
The average of Connecticut is 446762.125
The average of Delaware is 299311.3333333333
The average of District of Columbia is 601723.0
The average of Florida is 280616.5671641791
The average of Georgia is 60928.63522012578
The average of Hawaii is 272060.2
The average of Idaho is 35626.86363636364
The average of Illinois is 125790.50980392157
The average of Indiana is 70476.10869565218
The average of Iowa is 30771.262626262625
The average of Kansas is 27172.55238095238
The average of Kentucky is 36161.39166666667
The average of Louisiana is 70833.9375
The average of Maine is 83022.5625
The average of Maryland is 240564.66666666666
The average of Massachusetts is 467687.78571428574
The average of Michigan is 119080.0
The average of Minnesota is 60964.65517241379
The average of Mississippi is 36186.54878048781
The average of Missouri is 52077.62608695652
The average of Montana is 17668.125
The average of Nebraska is 19638.075268817203
The average of Nevada is 158855.9411764706
The average of New Hampshire is 131647.0
The average of New Jersey is 418661.61904761905
The average of New Mexico is 62399.36363636364
The average of New York is 312550.03225806454
The average of North Carolina is 95354.83
The average of North Dakota is 12690.396226415094
The average of Ohio is 131096.63636363635
The average of Oklahoma is 48718.844155844155
The average of Oregon is 106418.72222222222
The average of Pennsylvania is 189587.74626865672
The average of Rhode Island is 210513.4
The average of South Carolina is 100551.39130434782
The average of South Dakota is 12336.060606060606
The average of Tennessee is 66801.1052631579
The average of Texas is 98998.27165354331
The average of Utah is 95306.37931034483
The average of Vermont is 44695.78571428572
The average of Virginia is 60111.29323308271
The average of Washington is 172424.10256410256
The average of West Virginia is 33690.8
The average of Wisconsin is 78985.91666666667
The average of Wyoming is 24505.478260869564
The average of Alabama is 71339.34328358209
The average of Alaska is 24490.724137931036
The average of Arizona is 426134.4666666667
The average of Arkansas is 38878.90666666667
The average of California is 642309.5862068966
The average of Colorado is 78581.1875
The average of Connecticut is 446762.125
The average of Delaware is 299311.3333333333
The average of District of Columbia is 601723.0
The average of Florida is 280616.5671641791
The average of Georgia is 60928.63522012578
The average of Hawaii is 272060.2
The average of Idaho is 35626.86363636364
The average of Illinois is 125790.50980392157
The average of Indiana is 70476.10869565218
The average of Iowa is 30771.262626262625
The average of Kansas is 27172.55238095238
The average of Kentucky is 36161.39166666667
The average of Louisiana is 70833.9375
The average of Maine is 83022.5625
The average of Maryland is 240564.66666666666
The average of Massachusetts is 467687.78571428574
The average of Michigan is 119080.0
The average of Minnesota is 60964.65517241379
The average of Mississippi is 36186.54878048781
The average of Missouri is 52077.62608695652
The average of Montana is 17668.125
The average of Nebraska is 19638.075268817203
The average of Nevada is 158855.9411764706
The average of New Hampshire is 131647.0
The average of New Jersey is 418661.61904761905
The average of New Mexico is 62399.36363636364
The average of New York is 312550.03225806454
The average of North Carolina is 95354.83
The average of North Dakota is 12690.396226415094
The average of Ohio is 131096.63636363635
The average of Oklahoma is 48718.844155844155
The average of Oregon is 106418.72222222222
The average of Pennsylvania is 189587.74626865672
The average of Rhode Island is 210513.4
The average of South Carolina is 100551.39130434782
The average of South Dakota is 12336.060606060606
The average of Tennessee is 66801.1052631579
The average of Texas is 98998.27165354331
The average of Utah is 95306.37931034483
The average of Vermont is 44695.78571428572
The average of Virginia is 60111.29323308271
The average of Washington is 172424.10256410256
The average of West Virginia is 33690.8
The average of Wisconsin is 78985.91666666667
The average of Wyoming is 24505.478260869564
The average of Alabama is 71339.34328358209
The average of Alaska is 24490.724137931036
The average of Arizona is 426134.4666666667
The average of Arkansas is 38878.90666666667
The average of California is 642309.5862068966
The average of Colorado is 78581.1875
The average of Connecticut is 446762.125
The average of Delaware is 299311.3333333333
The average of District of Columbia is 601723.0
The average of Florida is 280616.5671641791
The average of Georgia is 60928.63522012578
The average of Hawaii is 272060.2
The average of Idaho is 35626.86363636364
The average of Illinois is 125790.50980392157
The average of Indiana is 70476.10869565218
The average of Iowa is 30771.262626262625
The average of Kansas is 27172.55238095238
The average of Kentucky is 36161.39166666667
The average of Louisiana is 70833.9375
The average of Maine is 83022.5625
The average of Maryland is 240564.66666666666
The average of Massachusetts is 467687.78571428574
The average of Michigan is 119080.0
The average of Minnesota is 60964.65517241379
The average of Mississippi is 36186.54878048781
The average of Missouri is 52077.62608695652
The average of Montana is 17668.125
The average of Nebraska is 19638.075268817203
The average of Nevada is 158855.9411764706
The average of New Hampshire is 131647.0
The average of New Jersey is 418661.61904761905
The average of New Mexico is 62399.36363636364
The average of New York is 312550.03225806454
The average of North Carolina is 95354.83
The average of North Dakota is 12690.396226415094
The average of Ohio is 131096.63636363635
The average of Oklahoma is 48718.844155844155
The average of Oregon is 106418.72222222222
The average of Pennsylvania is 189587.74626865672
The average of Rhode Island is 210513.4
The average of South Carolina is 100551.39130434782
The average of South Dakota is 12336.060606060606
The average of Tennessee is 66801.1052631579
The average of Texas is 98998.27165354331
The average of Utah is 95306.37931034483
The average of Vermont is 44695.78571428572
The average of Virginia is 60111.29323308271
The average of Washington is 172424.10256410256
The average of West Virginia is 33690.8
The average of Wisconsin is 78985.91666666667
The average of Wyoming is 24505.478260869564
The average of Alabama is 71339.34328358209
The average of Alaska is 24490.724137931036
The average of Arizona is 426134.4666666667
The average of Arkansas is 38878.90666666667
The average of California is 642309.5862068966
The average of Colorado is 78581.1875
The average of Connecticut is 446762.125
The average of Delaware is 299311.3333333333
The average of District of Columbia is 601723.0
The average of Florida is 280616.5671641791
The average of Georgia is 60928.63522012578
The average of Hawaii is 272060.2
The average of Idaho is 35626.86363636364
The average of Illinois is 125790.50980392157
The average of Indiana is 70476.10869565218
The average of Iowa is 30771.262626262625
The average of Kansas is 27172.55238095238
The average of Kentucky is 36161.39166666667
The average of Louisiana is 70833.9375
The average of Maine is 83022.5625
The average of Maryland is 240564.66666666666
The average of Massachusetts is 467687.78571428574
The average of Michigan is 119080.0
The average of Minnesota is 60964.65517241379
The average of Mississippi is 36186.54878048781
The average of Missouri is 52077.62608695652
The average of Montana is 17668.125
The average of Nebraska is 19638.075268817203
The average of Nevada is 158855.9411764706

The average of New Hampshire is 131647.0
The average of New Jersey is 418661.61904761905
The average of New Mexico is 62399.36363636364
The average of New York is 312550.03225806454
The average of North Carolina is 95354.83
The average of North Dakota is 12690.396226415094
The average of Ohio is 131096.63636363635
The average of Oklahoma is 48718.844155844155
The average of Oregon is 106418.72222222222
The average of Pennsylvania is 189587.74626865672
The average of Rhode Island is 210513.4
The average of South Carolina is 100551.39130434782
The average of South Dakota is 12336.060606060606
The average of Tennessee is 66801.1052631579
The average of Texas is 98998.27165354331
The average of Utah is 95306.37931034483
The average of Vermont is 44695.78571428572
The average of Virginia is 60111.29323308271
The average of Washington is 172424.10256410256
The average of West Virginia is 33690.8
The average of Wisconsin is 78985.91666666667
The average of Wyoming is 24505.478260869564
The average of Alabama is 71339.34328358209
The average of Alaska is 24490.724137931036
The average of Arizona is 426134.4666666667
The average of Arkansas is 38878.90666666667
The average of California is 642309.5862068966
The average of Colorado is 78581.1875
The average of Connecticut is 446762.125
The average of Delaware is 299311.3333333333
The average of District of Columbia is 601723.0
The average of Florida is 280616.5671641791
The average of Georgia is 60928.63522012578
The average of Hawaii is 272060.2
The average of Idaho is 35626.86363636364
The average of Illinois is 125790.50980392157
The average of Indiana is 70476.10869565218
The average of Iowa is 30771.262626262625
The average of Kansas is 27172.55238095238
The average of Kentucky is 36161.39166666667
The average of Louisiana is 70833.9375
The average of Maine is 83022.5625
The average of Maryland is 240564.66666666666
The average of Massachusetts is 467687.78571428574
The average of Michigan is 119080.0
The average of Minnesota is 60964.65517241379
The average of Mississippi is 36186.54878048781
The average of Missouri is 52077.62608695652
The average of Montana is 17668.125
The average of Nebraska is 19638.075268817203
The average of Nevada is 158855.9411764706
The average of New Hampshire is 131647.0
The average of New Jersey is 418661.61904761905
The average of New Mexico is 62399.36363636364
The average of New York is 312550.03225806454
The average of North Carolina is 95354.83
The average of North Dakota is 12690.396226415094
The average of Ohio is 131096.63636363635
The average of Oklahoma is 48718.844155844155
The average of Oregon is 106418.72222222222
The average of Pennsylvania is 189587.74626865672
The average of Rhode Island is 210513.4
The average of South Carolina is 100551.39130434782
The average of South Dakota is 12336.060606060606
The average of Tennessee is 66801.1052631579
The average of Texas is 98998.27165354331
The average of Utah is 95306.37931034483
The average of Vermont is 44695.78571428572
The average of Virginia is 60111.29323308271
The average of Washington is 172424.10256410256
The average of West Virginia is 33690.8
The average of Wisconsin is 78985.91666666667
The average of Wyoming is 24505.478260869564
The average of Alabama is 71339.34328358209
The average of Alaska is 24490.724137931036
The average of Arizona is 426134.4666666667
The average of Arkansas is 38878.90666666667
The average of California is 642309.5862068966
The average of Colorado is 78581.1875
The average of Connecticut is 446762.125
The average of Delaware is 299311.3333333333
The average of District of Columbia is 601723.0
The average of Florida is 280616.5671641791
The average of Georgia is 60928.63522012578
The average of Hawaii is 272060.2
The average of Idaho is 35626.86363636364
The average of Illinois is 125790.50980392157
The average of Indiana is 70476.10869565218
The average of Iowa is 30771.262626262625
The average of Kansas is 27172.55238095238
The average of Kentucky is 36161.39166666667
The average of Louisiana is 70833.9375
The average of Maine is 83022.5625
The average of Maryland is 240564.66666666666
The average of Massachusetts is 467687.78571428574
The average of Michigan is 119080.0
The average of Minnesota is 60964.65517241379
The average of Mississippi is 36186.54878048781
The average of Missouri is 52077.62608695652
The average of Montana is 17668.125
The average of Nebraska is 19638.075268817203
The average of Nevada is 158855.9411764706
The average of New Hampshire is 131647.0
The average of New Jersey is 418661.61904761905
The average of New Mexico is 62399.36363636364
The average of New York is 312550.03225806454
The average of North Carolina is 95354.83
The average of North Dakota is 12690.396226415094
The average of Ohio is 131096.63636363635
The average of Oklahoma is 48718.844155844155
The average of Oregon is 106418.72222222222
The average of Pennsylvania is 189587.74626865672
The average of Rhode Island is 210513.4
The average of South Carolina is 100551.39130434782
The average of South Dakota is 12336.060606060606
The average of Tennessee is 66801.1052631579
The average of Texas is 98998.27165354331
The average of Utah is 95306.37931034483
The average of Vermont is 44695.78571428572
The average of Virginia is 60111.29323308271
The average of Washington is 172424.10256410256
The average of West Virginia is 33690.8
The average of Wisconsin is 78985.91666666667
The average of Wyoming is 24505.478260869564
The average of Alabama is 71339.34328358209
The average of Alaska is 24490.724137931036
The average of Arizona is 426134.4666666667
The average of Arkansas is 38878.90666666667
The average of California is 642309.5862068966
The average of Colorado is 78581.1875
The average of Connecticut is 446762.125
The average of Delaware is 299311.3333333333
The average of District of Columbia is 601723.0
The average of Florida is 280616.5671641791
The average of Georgia is 60928.63522012578
The average of Hawaii is 272060.2
The average of Idaho is 35626.86363636364
The average of Illinois is 125790.50980392157
The average of Indiana is 70476.10869565218
The average of Iowa is 30771.262626262625
The average of Kansas is 27172.55238095238
The average of Kentucky is 36161.39166666667
The average of Louisiana is 70833.9375
The average of Maine is 83022.5625
The average of Maryland is 240564.66666666666
The average of Massachusetts is 467687.78571428574
The average of Michigan is 119080.0
The average of Minnesota is 60964.65517241379
The average of Mississippi is 36186.54878048781
The average of Missouri is 52077.62608695652
The average of Montana is 17668.125
The average of Nebraska is 19638.075268817203
The average of Nevada is 158855.9411764706
The average of New Hampshire is 131647.0
The average of New Jersey is 418661.61904761905
The average of New Mexico is 62399.36363636364
The average of New York is 312550.03225806454
The average of North Carolina is 95354.83
The average of North Dakota is 12690.396226415094
The average of Ohio is 131096.63636363635
The average of Oklahoma is 48718.844155844155
The average of Oregon is 106418.72222222222
The average of Pennsylvania is 189587.74626865672
The average of Rhode Island is 210513.4
The average of South Carolina is 100551.39130434782
The average of South Dakota is 12336.060606060606
The average of Tennessee is 66801.1052631579
The average of Texas is 98998.27165354331
The average of Utah is 95306.37931034483
The average of Vermont is 44695.78571428572
The average of Virginia is 60111.29323308271
The average of Washington is 172424.10256410256
The average of West Virginia is 33690.8
The average of Wisconsin is 78985.91666666667
The average of Wyoming is 24505.478260869564
The average of Alabama is 71339.34328358209
The average of Alaska is 24490.724137931036
The average of Arizona is 426134.4666666667
The average of Arkansas is 38878.90666666667
The average of California is 642309.5862068966
The average of Colorado is 78581.1875
The average of Connecticut is 446762.125
The average of Delaware is 299311.3333333333
The average of District of Columbia is 601723.0
The average of Florida is 280616.5671641791
The average of Georgia is 60928.63522012578
The average of Hawaii is 272060.2
The average of Idaho is 35626.86363636364
The average of Illinois is 125790.50980392157
The average of Indiana is 70476.10869565218
The average of Iowa is 30771.262626262625
The average of Kansas is 27172.55238095238
The average of Kentucky is 36161.39166666667
The average of Louisiana is 70833.9375
The average of Maine is 83022.5625
The average of Maryland is 240564.66666666666
The average of Massachusetts is 467687.78571428574
The average of Michigan is 119080.0
The average of Minnesota is 60964.65517241379
The average of Mississippi is 36186.54878048781
The average of Missouri is 52077.62608695652
The average of Montana is 17668.125
The average of Nebraska is 19638.075268817203
The average of Nevada is 158855.9411764706
The average of New Hampshire is 131647.0
The average of New Jersey is 418661.61904761905
The average of New Mexico is 62399.36363636364
The average of New York is 312550.03225806454
The average of North Carolina is 95354.83
The average of North Dakota is 12690.396226415094
The average of Ohio is 131096.63636363635
The average of Oklahoma is 48718.844155844155
The average of Oregon is 106418.72222222222
The average of Pennsylvania is 189587.74626865672
The average of Rhode Island is 210513.4
The average of South Carolina is 100551.39130434782
The average of South Dakota is 12336.060606060606
The average of Tennessee is 66801.1052631579
The average of Texas is 98998.27165354331
The average of Utah is 95306.37931034483
The average of Vermont is 44695.78571428572
The average of Virginia is 60111.29323308271
The average of Washington is 172424.10256410256
The average of West Virginia is 33690.8
The average of Wisconsin is 78985.91666666667
The average of Wyoming is 24505.478260869564
The average of Alabama is 71339.34328358209
The average of Alaska is 24490.724137931036
The average of Arizona is 426134.4666666667
The average of Arkansas is 38878.90666666667
The average of California is 642309.5862068966
The average of Colorado is 78581.1875
The average of Connecticut is 446762.125
The average of Delaware is 299311.3333333333
The average of District of Columbia is 601723.0
The average of Florida is 280616.5671641791
The average of Georgia is 60928.63522012578
The average of Hawaii is 272060.2
The average of Idaho is 35626.86363636364
The average of Illinois is 125790.50980392157
The average of Indiana is 70476.10869565218
The average of Iowa is 30771.262626262625
The average of Kansas is 27172.55238095238
The average of Kentucky is 36161.39166666667
The average of Louisiana is 70833.9375

The average of Maine is 83022.5625
The average of Maryland is 240564.66666666666
The average of Massachusetts is 467687.78571428574
The average of Michigan is 119080.0
The average of Minnesota is 60964.65517241379
The average of Mississippi is 36186.54878048781
The average of Missouri is 52077.62608695652
The average of Montana is 17668.125
The average of Nebraska is 19638.075268817203
The average of Nevada is 158855.9411764706
The average of New Hampshire is 131647.0
The average of New Jersey is 418661.61904761905
The average of New Mexico is 62399.36363636364
The average of New York is 312550.03225806454
The average of North Carolina is 95354.83
The average of North Dakota is 12690.396226415094
The average of Ohio is 131096.63636363635
The average of Oklahoma is 48718.844155844155
The average of Oregon is 106418.72222222222
The average of Pennsylvania is 189587.74626865672
The average of Rhode Island is 210513.4
The average of South Carolina is 100551.39130434782
The average of South Dakota is 12336.060606060606
The average of Tennessee is 66801.1052631579
The average of Texas is 98998.27165354331
The average of Utah is 95306.37931034483
The average of Vermont is 44695.78571428572
The average of Virginia is 60111.29323308271
The average of Washington is 172424.10256410256
The average of West Virginia is 33690.8
The average of Wisconsin is 78985.91666666667
The average of Wyoming is 24505.478260869564
The average of Alabama is 71339.34328358209
The average of Alaska is 24490.724137931036
The average of Arizona is 426134.4666666667
The average of Arkansas is 38878.90666666667
The average of California is 642309.5862068966
The average of Colorado is 78581.1875
The average of Connecticut is 446762.125
The average of Delaware is 299311.3333333333
The average of District of Columbia is 601723.0
The average of Florida is 280616.5671641791
The average of Georgia is 60928.63522012578
The average of Hawaii is 272060.2
The average of Idaho is 35626.86363636364
The average of Illinois is 125790.50980392157
The average of Indiana is 70476.10869565218
The average of Iowa is 30771.262626262625
The average of Kansas is 27172.55238095238
The average of Kentucky is 36161.39166666667
The average of Louisiana is 70833.9375
The average of Maine is 83022.5625
The average of Maryland is 240564.66666666666
The average of Massachusetts is 467687.78571428574
The average of Michigan is 119080.0
The average of Minnesota is 60964.65517241379
The average of Mississippi is 36186.54878048781
The average of Missouri is 52077.62608695652
The average of Montana is 17668.125
The average of Nebraska is 19638.075268817203
The average of Nevada is 158855.9411764706
The average of New Hampshire is 131647.0
The average of New Jersey is 418661.61904761905
The average of New Mexico is 62399.36363636364
The average of New York is 312550.03225806454
The average of North Carolina is 95354.83
The average of North Dakota is 12690.396226415094
The average of Ohio is 131096.63636363635
The average of Oklahoma is 48718.844155844155
The average of Oregon is 106418.72222222222
The average of Pennsylvania is 189587.74626865672
The average of Rhode Island is 210513.4
The average of South Carolina is 100551.39130434782
The average of South Dakota is 12336.060606060606
The average of Tennessee is 66801.1052631579
The average of Texas is 98998.27165354331
The average of Utah is 95306.37931034483
The average of Vermont is 44695.78571428572
The average of Virginia is 60111.29323308271
The average of Washington is 172424.10256410256
The average of West Virginia is 33690.8
The average of Wisconsin is 78985.91666666667
The average of Wyoming is 24505.478260869564
The average of Alabama is 71339.34328358209
The average of Alaska is 24490.724137931036
The average of Arizona is 426134.4666666667
The average of Arkansas is 38878.90666666667
The average of California is 642309.5862068966
The average of Colorado is 78581.1875
The average of Connecticut is 446762.125
The average of Delaware is 299311.3333333333
The average of District of Columbia is 601723.0
The average of Florida is 280616.5671641791
The average of Georgia is 60928.63522012578
The average of Hawaii is 272060.2
The average of Idaho is 35626.86363636364
The average of Illinois is 125790.50980392157
The average of Indiana is 70476.10869565218
The average of Iowa is 30771.262626262625
The average of Kansas is 27172.55238095238
The average of Kentucky is 36161.39166666667
The average of Louisiana is 70833.9375
The average of Maine is 83022.5625
The average of Maryland is 240564.66666666666
The average of Massachusetts is 467687.78571428574
The average of Michigan is 119080.0
The average of Minnesota is 60964.65517241379
The average of Mississippi is 36186.54878048781
The average of Missouri is 52077.62608695652
The average of Montana is 17668.125
The average of Nebraska is 19638.075268817203
The average of Nevada is 158855.9411764706
The average of New Hampshire is 131647.0
The average of New Jersey is 418661.61904761905
The average of New Mexico is 62399.36363636364
The average of New York is 312550.03225806454
The average of North Carolina is 95354.83
The average of North Dakota is 12690.396226415094
The average of Ohio is 131096.63636363635
The average of Oklahoma is 48718.844155844155
The average of Oregon is 106418.72222222222
The average of Pennsylvania is 189587.74626865672
The average of Rhode Island is 210513.4
The average of South Carolina is 100551.39130434782
The average of South Dakota is 12336.060606060606
The average of Tennessee is 66801.1052631579
The average of Texas is 98998.27165354331
The average of Utah is 95306.37931034483
The average of Vermont is 44695.78571428572
The average of Virginia is 60111.29323308271
The average of Washington is 172424.10256410256
The average of West Virginia is 33690.8
The average of Wisconsin is 78985.91666666667
The average of Wyoming is 24505.478260869564
The average of Alabama is 71339.34328358209
The average of Alaska is 24490.724137931036
The average of Arizona is 426134.4666666667
The average of Arkansas is 38878.90666666667
The average of California is 642309.5862068966
The average of Colorado is 78581.1875
The average of Connecticut is 446762.125
The average of Delaware is 299311.3333333333
The average of District of Columbia is 601723.0
The average of Florida is 280616.5671641791
The average of Georgia is 60928.63522012578
The average of Hawaii is 272060.2
The average of Idaho is 35626.86363636364
The average of Illinois is 125790.50980392157
The average of Indiana is 70476.10869565218
The average of Iowa is 30771.262626262625
The average of Kansas is 27172.55238095238
The average of Kentucky is 36161.39166666667
The average of Louisiana is 70833.9375
The average of Maine is 83022.5625
The average of Maryland is 240564.66666666666
The average of Massachusetts is 467687.78571428574
The average of Michigan is 119080.0
The average of Minnesota is 60964.65517241379
The average of Mississippi is 36186.54878048781
The average of Missouri is 52077.62608695652
The average of Montana is 17668.125
The average of Nebraska is 19638.075268817203
The average of Nevada is 158855.9411764706
The average of New Hampshire is 131647.0
The average of New Jersey is 418661.61904761905
The average of New Mexico is 62399.36363636364
The average of New York is 312550.03225806454
The average of North Carolina is 95354.83
The average of North Dakota is 12690.396226415094
The average of Ohio is 131096.63636363635
The average of Oklahoma is 48718.844155844155
The average of Oregon is 106418.72222222222
The average of Pennsylvania is 189587.74626865672
The average of Rhode Island is 210513.4
The average of South Carolina is 100551.39130434782
The average of South Dakota is 12336.060606060606
The average of Tennessee is 66801.1052631579
The average of Texas is 98998.27165354331
The average of Utah is 95306.37931034483
The average of Vermont is 44695.78571428572
The average of Virginia is 60111.29323308271
The average of Washington is 172424.10256410256
The average of West Virginia is 33690.8
The average of Wisconsin is 78985.91666666667
The average of Wyoming is 24505.478260869564
The average of Alabama is 71339.34328358209
The average of Alaska is 24490.724137931036
The average of Arizona is 426134.4666666667
The average of Arkansas is 38878.90666666667
The average of California is 642309.5862068966
The average of Colorado is 78581.1875
The average of Connecticut is 446762.125
The average of Delaware is 299311.3333333333
The average of District of Columbia is 601723.0
The average of Florida is 280616.5671641791
The average of Georgia is 60928.63522012578
The average of Hawaii is 272060.2
The average of Idaho is 35626.86363636364
The average of Illinois is 125790.50980392157
The average of Indiana is 70476.10869565218
The average of Iowa is 30771.262626262625
The average of Kansas is 27172.55238095238
The average of Kentucky is 36161.39166666667
The average of Louisiana is 70833.9375
The average of Maine is 83022.5625
The average of Maryland is 240564.66666666666
The average of Massachusetts is 467687.78571428574
The average of Michigan is 119080.0
The average of Minnesota is 60964.65517241379
The average of Mississippi is 36186.54878048781
The average of Missouri is 52077.62608695652
The average of Montana is 17668.125
The average of Nebraska is 19638.075268817203
The average of Nevada is 158855.9411764706
The average of New Hampshire is 131647.0
The average of New Jersey is 418661.61904761905
The average of New Mexico is 62399.36363636364
The average of New York is 312550.03225806454
The average of North Carolina is 95354.83
The average of North Dakota is 12690.396226415094
The average of Ohio is 131096.63636363635
The average of Oklahoma is 48718.844155844155
The average of Oregon is 106418.72222222222
The average of Pennsylvania is 189587.74626865672
The average of Rhode Island is 210513.4
The average of South Carolina is 100551.39130434782
The average of South Dakota is 12336.060606060606
The average of Tennessee is 66801.1052631579
The average of Texas is 98998.27165354331
The average of Utah is 95306.37931034483
The average of Vermont is 44695.78571428572
The average of Virginia is 60111.29323308271
The average of Washington is 172424.10256410256
The average of West Virginia is 33690.8
The average of Wisconsin is 78985.91666666667
The average of Wyoming is 24505.478260869564
The average of Alabama is 71339.34328358209
The average of Alaska is 24490.724137931036
The average of Arizona is 426134.4666666667
The average of Arkansas is 38878.90666666667
The average of California is 642309.5862068966
The average of Colorado is 78581.1875
The average of Connecticut is 446762.125
The average of Delaware is 299311.3333333333
The average of District of Columbia is 601723.0
The average of Florida is 280616.5671641791
The average of Georgia is 60928.63522012578
The average of Hawaii is 272060.2

The average of Idaho is 35626.86363636364
The average of Illinois is 125790.50980392157
The average of Indiana is 70476.10869565218
The average of Iowa is 30771.262626262625
The average of Kansas is 27172.55238095238
The average of Kentucky is 36161.39166666667
The average of Louisiana is 70833.9375
The average of Maine is 83022.5625
The average of Maryland is 240564.66666666666
The average of Massachusetts is 467687.78571428574
The average of Michigan is 119080.0
The average of Minnesota is 60964.65517241379
The average of Mississippi is 36186.54878048781
The average of Missouri is 52077.62608695652
The average of Montana is 17668.125
The average of Nebraska is 19638.075268817203
The average of Nevada is 158855.9411764706
The average of New Hampshire is 131647.0
The average of New Jersey is 418661.61904761905
The average of New Mexico is 62399.36363636364
The average of New York is 312550.03225806454
The average of North Carolina is 95354.83
The average of North Dakota is 12690.396226415094
The average of Ohio is 131096.63636363635
The average of Oklahoma is 48718.844155844155
The average of Oregon is 106418.72222222222
The average of Pennsylvania is 189587.74626865672
The average of Rhode Island is 210513.4
The average of South Carolina is 100551.39130434782
The average of South Dakota is 12336.060606060606
The average of Tennessee is 66801.1052631579
The average of Texas is 98998.27165354331
The average of Utah is 95306.37931034483
The average of Vermont is 44695.78571428572
The average of Virginia is 60111.29323308271
The average of Washington is 172424.10256410256
The average of West Virginia is 33690.8
The average of Wisconsin is 78985.91666666667
The average of Wyoming is 24505.478260869564
The average of Alabama is 71339.34328358209
The average of Alaska is 24490.724137931036
The average of Arizona is 426134.4666666667
The average of Arkansas is 38878.90666666667
The average of California is 642309.5862068966
The average of Colorado is 78581.1875
The average of Connecticut is 446762.125
The average of Delaware is 299311.3333333333
The average of District of Columbia is 601723.0
The average of Florida is 280616.5671641791
The average of Georgia is 60928.63522012578
The average of Hawaii is 272060.2
The average of Idaho is 35626.86363636364
The average of Illinois is 125790.50980392157
The average of Indiana is 70476.10869565218
The average of Iowa is 30771.262626262625
The average of Kansas is 27172.55238095238
The average of Kentucky is 36161.39166666667
The average of Louisiana is 70833.9375
The average of Maine is 83022.5625
The average of Maryland is 240564.66666666666
The average of Massachusetts is 467687.78571428574
The average of Michigan is 119080.0
The average of Minnesota is 60964.65517241379
The average of Mississippi is 36186.54878048781
The average of Missouri is 52077.62608695652
The average of Montana is 17668.125
The average of Nebraska is 19638.075268817203
The average of Nevada is 158855.9411764706
The average of New Hampshire is 131647.0
The average of New Jersey is 418661.61904761905
The average of New Mexico is 62399.36363636364
The average of New York is 312550.03225806454
The average of North Carolina is 95354.83
The average of North Dakota is 12690.396226415094
The average of Ohio is 131096.63636363635
The average of Oklahoma is 48718.844155844155
The average of Oregon is 106418.72222222222
The average of Pennsylvania is 189587.74626865672
The average of Rhode Island is 210513.4
The average of South Carolina is 100551.39130434782
The average of South Dakota is 12336.060606060606
The average of Tennessee is 66801.1052631579
The average of Texas is 98998.27165354331
The average of Utah is 95306.37931034483
The average of Vermont is 44695.78571428572
The average of Virginia is 60111.29323308271
The average of Washington is 172424.10256410256
The average of West Virginia is 33690.8
The average of Wisconsin is 78985.91666666667
The average of Wyoming is 24505.478260869564
The average of Alabama is 71339.34328358209
The average of Alaska is 24490.724137931036
The average of Arizona is 426134.4666666667
The average of Arkansas is 38878.90666666667
The average of California is 642309.5862068966
The average of Colorado is 78581.1875
The average of Connecticut is 446762.125
The average of Delaware is 299311.3333333333
The average of District of Columbia is 601723.0
The average of Florida is 280616.5671641791
The average of Georgia is 60928.63522012578
The average of Hawaii is 272060.2
The average of Idaho is 35626.86363636364
The average of Illinois is 125790.50980392157
The average of Indiana is 70476.10869565218
The average of Iowa is 30771.262626262625
The average of Kansas is 27172.55238095238
The average of Kentucky is 36161.39166666667
The average of Louisiana is 70833.9375
The average of Maine is 83022.5625
The average of Maryland is 240564.66666666666
The average of Massachusetts is 467687.78571428574
The average of Michigan is 119080.0
The average of Minnesota is 60964.65517241379
The average of Mississippi is 36186.54878048781
The average of Missouri is 52077.62608695652
The average of Montana is 17668.125
The average of Nebraska is 19638.075268817203
The average of Nevada is 158855.9411764706
The average of New Hampshire is 131647.0
The average of New Jersey is 418661.61904761905
The average of New Mexico is 62399.36363636364
The average of New York is 312550.03225806454
The average of North Carolina is 95354.83
The average of North Dakota is 12690.396226415094
The average of Ohio is 131096.63636363635
The average of Oklahoma is 48718.844155844155
The average of Oregon is 106418.72222222222
The average of Pennsylvania is 189587.74626865672
The average of Rhode Island is 210513.4
The average of South Carolina is 100551.39130434782
The average of South Dakota is 12336.060606060606
The average of Tennessee is 66801.1052631579
The average of Texas is 98998.27165354331
The average of Utah is 95306.37931034483
The average of Vermont is 44695.78571428572
The average of Virginia is 60111.29323308271
The average of Washington is 172424.10256410256
The average of West Virginia is 33690.8
The average of Wisconsin is 78985.91666666667
The average of Wyoming is 24505.478260869564
The average of Alabama is 71339.34328358209
The average of Alaska is 24490.724137931036
The average of Arizona is 426134.4666666667
The average of Arkansas is 38878.90666666667
The average of California is 642309.5862068966
The average of Colorado is 78581.1875
The average of Connecticut is 446762.125
The average of Delaware is 299311.3333333333
The average of District of Columbia is 601723.0
The average of Florida is 280616.5671641791
The average of Georgia is 60928.63522012578
The average of Hawaii is 272060.2
The average of Idaho is 35626.86363636364
The average of Illinois is 125790.50980392157
The average of Indiana is 70476.10869565218
The average of Iowa is 30771.262626262625
The average of Kansas is 27172.55238095238
The average of Kentucky is 36161.39166666667
The average of Louisiana is 70833.9375
The average of Maine is 83022.5625
The average of Maryland is 240564.66666666666
The average of Massachusetts is 467687.78571428574
The average of Michigan is 119080.0
The average of Minnesota is 60964.65517241379
The average of Mississippi is 36186.54878048781
The average of Missouri is 52077.62608695652
The average of Montana is 17668.125
The average of Nebraska is 19638.075268817203
The average of Nevada is 158855.9411764706
The average of New Hampshire is 131647.0
The average of New Jersey is 418661.61904761905
The average of New Mexico is 62399.36363636364
The average of New York is 312550.03225806454
The average of North Carolina is 95354.83
The average of North Dakota is 12690.396226415094
The average of Ohio is 131096.63636363635
The average of Oklahoma is 48718.844155844155
The average of Oregon is 106418.72222222222
The average of Pennsylvania is 189587.74626865672
The average of Rhode Island is 210513.4
The average of South Carolina is 100551.39130434782
The average of South Dakota is 12336.060606060606
The average of Tennessee is 66801.1052631579
The average of Texas is 98998.27165354331
The average of Utah is 95306.37931034483
The average of Vermont is 44695.78571428572
The average of Virginia is 60111.29323308271
The average of Washington is 172424.10256410256
The average of West Virginia is 33690.8
The average of Wisconsin is 78985.91666666667
The average of Wyoming is 24505.478260869564
The average of Alabama is 71339.34328358209
The average of Alaska is 24490.724137931036
The average of Arizona is 426134.4666666667
The average of Arkansas is 38878.90666666667
The average of California is 642309.5862068966
The average of Colorado is 78581.1875
The average of Connecticut is 446762.125
The average of Delaware is 299311.3333333333
The average of District of Columbia is 601723.0
The average of Florida is 280616.5671641791
The average of Georgia is 60928.63522012578
The average of Hawaii is 272060.2
The average of Idaho is 35626.86363636364
The average of Illinois is 125790.50980392157
The average of Indiana is 70476.10869565218
The average of Iowa is 30771.262626262625
The average of Kansas is 27172.55238095238
The average of Kentucky is 36161.39166666667
The average of Louisiana is 70833.9375
The average of Maine is 83022.5625
The average of Maryland is 240564.66666666666
The average of Massachusetts is 467687.78571428574
The average of Michigan is 119080.0
The average of Minnesota is 60964.65517241379
The average of Mississippi is 36186.54878048781
The average of Missouri is 52077.62608695652
The average of Montana is 17668.125
The average of Nebraska is 19638.075268817203
The average of Nevada is 158855.9411764706
The average of New Hampshire is 131647.0
The average of New Jersey is 418661.61904761905
The average of New Mexico is 62399.36363636364
The average of New York is 312550.03225806454
The average of North Carolina is 95354.83
The average of North Dakota is 12690.396226415094
The average of Ohio is 131096.63636363635
The average of Oklahoma is 48718.844155844155
The average of Oregon is 106418.72222222222
The average of Pennsylvania is 189587.74626865672
The average of Rhode Island is 210513.4
The average of South Carolina is 100551.39130434782
The average of South Dakota is 12336.060606060606
The average of Tennessee is 66801.1052631579
The average of Texas is 98998.27165354331
The average of Utah is 95306.37931034483
The average of Vermont is 44695.78571428572
The average of Virginia is 60111.29323308271
The average of Washington is 172424.10256410256
The average of West Virginia is 33690.8
The average of Wisconsin is 78985.91666666667
The average of Wyoming is 24505.478260869564
The average of Alabama is 71339.34328358209
The average of Alaska is 24490.724137931036
The average of Arizona is 426134.4666666667
The average of Arkansas is 38878.90666666667
The average of California is 642309.5862068966
The average of Colorado is 78581.1875
The average of Connecticut is 446762.125
The average of Delaware is 299311.3333333333
The average of District of Columbia is 601723.0
The average of Florida is 280616.5671641791
The average of Georgia is 60928.63522012578
The average of Hawaii is 272060.2
The average of Idaho is 35626.86363636364

The average of Illinois is 125790.50980392157
The average of Indiana is 70476.10869565218
The average of Iowa is 30771.262626262625
The average of Kansas is 27172.55238095238
The average of Kentucky is 36161.39166666667
The average of Louisiana is 70833.9375
The average of Maine is 83022.5625
The average of Maryland is 240564.66666666666
The average of Massachusetts is 467687.78571428574
The average of Michigan is 119080.0
The average of Minnesota is 60964.65517241379
The average of Mississippi is 36186.54878048781
The average of Missouri is 52077.62608695652
The average of Montana is 17668.125
The average of Nebraska is 19638.075268817203
The average of Nevada is 158855.9411764706
The average of New Hampshire is 131647.0
The average of New Jersey is 418661.61904761905
The average of New Mexico is 62399.36363636364
The average of New York is 312550.03225806454
The average of North Carolina is 95354.83
The average of North Dakota is 12690.396226415094
The average of Ohio is 131096.63636363635
The average of Oklahoma is 48718.844155844155
The average of Oregon is 106418.72222222222
The average of Pennsylvania is 189587.74626865672
The average of Rhode Island is 210513.4
The average of South Carolina is 100551.39130434782
The average of South Dakota is 12336.060606060606
The average of Tennessee is 66801.1052631579
The average of Texas is 98998.27165354331
The average of Utah is 95306.37931034483
The average of Vermont is 44695.78571428572
The average of Virginia is 60111.29323308271
The average of Washington is 172424.10256410256
The average of West Virginia is 33690.8
The average of Wisconsin is 78985.91666666667
The average of Wyoming is 24505.478260869564
The average of Alabama is 71339.34328358209
The average of Alaska is 24490.724137931036
The average of Arizona is 426134.4666666667
The average of Arkansas is 38878.90666666667
The average of California is 642309.5862068966
The average of Colorado is 78581.1875
The average of Connecticut is 446762.125
The average of Delaware is 299311.3333333333
The average of District of Columbia is 601723.0
The average of Florida is 280616.5671641791
The average of Georgia is 60928.63522012578
The average of Hawaii is 272060.2
The average of Idaho is 35626.86363636364
The average of Illinois is 125790.50980392157
The average of Indiana is 70476.10869565218
The average of Iowa is 30771.262626262625
The average of Kansas is 27172.55238095238
The average of Kentucky is 36161.39166666667
The average of Louisiana is 70833.9375
The average of Maine is 83022.5625
The average of Maryland is 240564.66666666666
The average of Massachusetts is 467687.78571428574
The average of Michigan is 119080.0
The average of Minnesota is 60964.65517241379
The average of Mississippi is 36186.54878048781
The average of Missouri is 52077.62608695652
The average of Montana is 17668.125
The average of Nebraska is 19638.075268817203
The average of Nevada is 158855.9411764706
The average of New Hampshire is 131647.0
The average of New Jersey is 418661.61904761905
The average of New Mexico is 62399.36363636364
The average of New York is 312550.03225806454
The average of North Carolina is 95354.83
The average of North Dakota is 12690.396226415094
The average of Ohio is 131096.63636363635
The average of Oklahoma is 48718.844155844155
The average of Oregon is 106418.72222222222
The average of Pennsylvania is 189587.74626865672
The average of Rhode Island is 210513.4
The average of South Carolina is 100551.39130434782
The average of South Dakota is 12336.060606060606
The average of Tennessee is 66801.1052631579
The average of Texas is 98998.27165354331
The average of Utah is 95306.37931034483
The average of Vermont is 44695.78571428572
The average of Virginia is 60111.29323308271
The average of Washington is 172424.10256410256
The average of West Virginia is 33690.8
The average of Wisconsin is 78985.91666666667
The average of Wyoming is 24505.478260869564
40.4 ms ± 3.9 ms per loop (mean ± std. dev. of 7 runs, 3 loops each)

In [8]:
# We'll create some new function called set_batch_number and if the first letter of the parameter is a capital
# M we'll return a 0. If it's a capital Q we'll return a 1 and otherwise we'll return a 2. Then we'll pass
# this function to the data frame

df = df.set_index('STNAME')

def set_batch_number(item):
    if item[0]<'M':
        return 0
    if item[0]<'Q':
        return 1
    return 2

# The dataframe is supposed to be grouped by according to the batch number And we will loop through each batch
# group
for group, frame in df.groupby(by=set_batch_number):
    print('There are ' + str(len(frame)) + ' records in group ' + str(group) + ' for processing.')

There are 1177 records in group 0 for processing.
There are 1134 records in group 1 for processing.
There are 831 records in group 2 for processing.

**It's important to note that in order to do this you need to set the index of the data frame to be the column that you want to group by first.**

In [9]:
df = pd.read_csv('census.csv')
df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861

In [10]:
df=df.set_index(['SUMLEV', 'CENSUS2010POP'])

# When we have a multiindex we need to pass in the levels we are interested in grouping by
for group, frame in df.groupby(level=(0,1)):
    print(group)

(40, 563626)
(40, 601723)
(40, 625741)
(40, 672591)
(40, 710231)
(40, 814180)
(40, 897934)
(40, 989415)
(40, 1052567)
(40, 1316470)
(40, 1328361)
(40, 1360301)
(40, 1567582)
(40, 1826341)
(40, 1852994)
(40, 2059179)
(40, 2700551)
(40, 2763885)
(40, 2853118)
(40, 2915918)
(40, 2967297)
(40, 3046355)
(40, 3574097)
(40, 3751351)
(40, 3831074)
(40, 4339367)
(40, 4533372)
(40, 4625364)
(40, 4779736)
(40, 5029196)
(40, 5303925)
(40, 5686986)
(40, 5773552)
(40, 5988927)
(40, 6346105)
(40, 6392017)
(40, 6483802)
(40, 6547629)
(40, 6724540)
(40, 8001024)
(40, 8791894)
(40, 9535483)
(40, 9687653)
(40, 9883640)
(40, 11536504)
(40, 12702379)
(40, 12830632)
(40, 18801310)
(40, 19378102)
(40, 25145561)
(40, 37253956)
(50, 82)
(50, 90)
(50, 286)
(50, 416)
(50, 460)
(50, 478)
(50, 494)
(50, 539)
(50, 614)
(50, 632)
(50, 641)
(50, 647)
(50, 662)
(50, 690)
(50, 695)
(50, 699)
(50, 707)
(50, 712)
(50, 718)
(50, 727)
(50, 736)
(50, 763)
(50, 783)
(50, 808)
(50, 818)
(50, 824)
(50, 843)
(50, 884)
(50, 929)
(50, 967)
(50, 968)
(50, 982)
(50, 984)
(50, 997)
(50, 1006)
(50, 1017)
(50, 1059)
(50, 1117)
(50, 1143)
(50, 1160)
(50, 1175)
(50, 1179)
(50, 1206)
(50, 1210)
(50, 1226)
(50, 1247)
(50, 1255)
(50, 1311)
(50, 1321)
(50, 1336)
(50, 1373)
(50, 1394)
(50, 1398)
(50, 1406)
(50, 1420)
(50, 1441)
(50, 1466)
(50, 1485)
(50, 1490)
(50, 1505)
(50, 1526)
(50, 1556)
(50, 1599)
(50, 1631)
(50, 1637)
(50, 1641)
(50, 1680)
(50, 1717)
(50, 1734)
(50, 1743)
(50, 1750)
(50, 1751)
(50, 1765)
(50, 1826)
(50, 1836)
(50, 1846)
(50, 1871)
(50, 1891)
(50, 1901)
(50, 1912)
(50, 1916)
(50, 1937)
(50, 1941)
(50, 1968)
(50, 1975)
(50, 1987)
(50, 1990)
(50, 2002)
(50, 2008)
(50, 2022)
(50, 2044)
(50, 2048)
(50, 2049)
(50, 2052)
(50, 2057)
(50, 2064)
(50, 2071)
(50, 2072)
(50, 2099)
(50, 2150)
(50, 2156)
(50, 2168)
(50, 2171)
(50, 2215)
(50, 2234)
(50, 2235)
(50, 2242)
(50, 2246)
(50, 2264)
(50, 2266)
(50, 2282)
(50, 2321)
(50, 2329)
(50, 2339)
(50, 2342)
(50, 2343)
(50, 2355)
(50, 2364)
(50, 2369)
(50, 2379)
(50, 2385)
(50, 2389)
(50, 2394)
(50, 2398)
(50, 2420)
(50, 2435)
(50, 2444)
(50, 2459)
(50, 2470)
(50, 2475)
(50, 2477)
(50, 2484)
(50, 2508)
(50, 2513)
(50, 2519)
(50, 2538)
(50, 2553)
(50, 2556)
(50, 2597)
(50, 2690)
(50, 2695)
(50, 2710)
(50, 2726)
(50, 2756)
(50, 2773)
(50, 2778)
(50, 2790)
(50, 2799)
(50, 2801)
(50, 2809)
(50, 2882)
(50, 2890)
(50, 2891)
(50, 2908)
(50, 2922)
(50, 2961)
(50, 2966)
(50, 2970)
(50, 2982)
(50, 3001)
(50, 3002)
(50, 3031)
(50, 3034)
(50, 3037)
(50, 3057)
(50, 3077)
(50, 3079)
(50, 3082)
(50, 3107)
(50, 3126)
(50, 3127)
(50, 3141)
(50, 3145)
(50, 3151)
(50, 3152)
(50, 3183)
(50, 3225)
(50, 3233)
(50, 3240)
(50, 3241)
(50, 3302)
(50, 3307)
(50, 3309)
(50, 3320)
(50, 3331)
(50, 3343)
(50, 3353)
(50, 3355)
(50, 3367)
(50, 3378)
(50, 3384)
(50, 3423)
(50, 3431)
(50, 3451)
(50, 3461)
(50, 3476)
(50, 3524)
(50, 3536)
(50, 3550)
(50, 3558)
(50, 3598)
(50, 3647)
(50, 3651)
(50, 3669)
(50, 3677)
(50, 3685)
(50, 3691)
(50, 3719)
(50, 3725)
(50, 3726)
(50, 3735)
(50, 3755)
(50, 3785)
(50, 3788)
(50, 3807)
(50, 3812)
(50, 3815)
(50, 3821)
(50, 3829)
(50, 3853)
(50, 3858)
(50, 3958)
(50, 3966)
(50, 3974)
(50, 3976)
(50, 3977)
(50, 3978)
(50, 3993)
(50, 4010)
(50, 4012)
(50, 4029)
(50, 4034)
(50, 4045)
(50, 4050)
(50, 4071)
(50, 4078)
(50, 4087)
(50, 4089)
(50, 4128)
(50, 4131)
(50, 4139)
(50, 4151)
(50, 4153)
(50, 4207)
(50, 4223)
(50, 4232)
(50, 4253)
(50, 4255)
(50, 4256)
(50, 4260)
(50, 4271)
(50, 4286)
(50, 4320)
(50, 4357)
(50, 4364)
(50, 4368)
(50, 4375)
(50, 4407)
(50, 4423)
(50, 4431)
(50, 4436)
(50, 4437)
(50, 4442)
(50, 4470)
(50, 4500)
(50, 4527)
(50, 4538)
(50, 4549)
(50, 4552)
(50, 4575)
(50, 4607)
(50, 4656)
(50, 4687)
(50, 4731)
(50, 4755)
(50, 4772)
(50, 4799)
(50, 4810)
(50, 4812)
(50, 4814)
(50, 4836)
(50, 4843)
(50, 4847)
(50, 4861)
(50, 4881)
(50, 4894)
(50, 4902)
(50, 4912)
(50, 4916)
(50, 4936)
(50, 4959)
(50, 4979)
(50, 4980)
(50, 5010)
(50, 5042)
(50, 5077)
(50, 5085)
(50, 5089)
(50, 5104)
(50, 5131)
(50, 5148)
(50, 5172)
(50, 5176)
(50, 5181)
(50, 5190)
(50, 5208)
(50, 5217)
(50, 5228)
(50, 5231)
(50, 5252)
(50, 5255)
(50, 5269)
(50, 5289)
(50, 5300)
(50, 5301)
(50, 5324)
(50, 5345)
(50, 5355)
(50, 5368)
(50, 5395)
(50, 5406)
(50, 5410)
(50, 5413)
(50, 5438)
(50, 5441)
(50, 5457)
(50, 5467)
(50, 5469)
(50, 5505)
(50, 5548)
(50, 5559)
(50, 5561)
(50, 5588)
(50, 5589)
(50, 5612)
(50, 5613)
(50, 5618)
(50, 5636)
(50, 5642)
(50, 5644)
(50, 5671)
(50, 5685)
(50, 5710)
(50, 5713)
(50, 5717)
(50, 5724)
(50, 5775)
(50, 5799)
(50, 5810)
(50, 5813)
(50, 5823)
(50, 5834)
(50, 5890)
(50, 5896)
(50, 5899)
(50, 5903)
(50, 5915)
(50, 5916)
(50, 5923)
(50, 5925)
(50, 5927)
(50, 5961)
(50, 5986)
(50, 5994)
(50, 6000)
(50, 6006)
(50, 6010)
(50, 6018)
(50, 6034)
(50, 6058)
(50, 6059)
(50, 6062)
(50, 6073)
(50, 6091)
(50, 6108)
(50, 6119)
(50, 6125)
(50, 6128)
(50, 6129)
(50, 6131)
(50, 6153)
(50, 6161)
(50, 6182)
(50, 6193)
(50, 6239)
(50, 6265)
(50, 6274)
(50, 6306)
(50, 6317)
(50, 6360)
(50, 6362)
(50, 6373)
(50, 6403)
(50, 6415)
(50, 6428)
(50, 6429)
(50, 6446)
(50, 6461)
(50, 6462)
(50, 6472)
(50, 6486)
(50, 6489)
(50, 6491)
(50, 6497)
(50, 6499)
(50, 6542)
(50, 6576)
(50, 6629)
(50, 6631)
(50, 6650)
(50, 6660)
(50, 6666)
(50, 6685)
(50, 6689)
(50, 6694)
(50, 6696)
(50, 6703)
(50, 6711)
(50, 6714)
(50, 6721)
(50, 6738)
(50, 6753)
(50, 6780)
(50, 6798)
(50, 6813)
(50, 6819)
(50, 6824)
(50, 6839)
(50, 6852)
(50, 6856)
(50, 6858)
(50, 6865)
(50, 6885)
(50, 6886)
(50, 6937)
(50, 6940)
(50, 6945)
(50, 6963)
(50, 6970)
(50, 6973)
(50, 7008)
(50, 7027)
(50, 7028)
(50, 7029)
(50, 7041)
(50, 7042)
(50, 7053)
(50, 7058)
(50, 7070)
(50, 7083)
(50, 7089)
(50, 7094)
(50, 7110)
(50, 7125)
(50, 7135)
(50, 7139)
(50, 7141)
(50, 7165)
(50, 7208)
(50, 7210)
(50, 7223)
(50, 7248)
(50, 7256)
(50, 7259)
(50, 7260)
(50, 7266)
(50, 7310)
(50, 7331)
(50, 7343)
(50, 7355)
(50, 7356)
(50, 7359)
(50, 7369)
(50, 7373)
(50, 7383)
(50, 7413)
(50, 7421)
(50, 7422)
(50, 7441)
(50, 7445)
(50, 7459)
(50, 7469)
(50, 7516)
(50, 7523)
(50, 7527)
(50, 7544)
(50, 7547)
(50, 7551)
(50, 7570)
(50, 7598)
(50, 7605)
(50, 7627)
(50, 7645)
(50, 7673)
(50, 7682)
(50, 7691)
(50, 7695)
(50, 7716)
(50, 7719)
(50, 7726)
(50, 7759)
(50, 7817)
(50, 7818)
(50, 7829)
(50, 7831)
(50, 7832)
(50, 7845)
(50, 7852)
(50, 7854)
(50, 7858)
(50, 7861)
(50, 7870)
(50, 7879)
(50, 7883)
(50, 7887)
(50, 7895)
(50, 7900)
(50, 7915)
(50, 7936)
(50, 7945)
(50, 7970)
(50, 7992)
(50, 7996)
(50, 8062)
(50, 8102)
(50, 8116)
(50, 8118)
(50, 8121)
(50, 8149)
(50, 8195)
(50, 8202)
(50, 8216)
(50, 8223)
(50, 8238)
(50, 8249)
(50, 8256)
(50, 8270)
(50, 8283)
(50, 8314)
(50, 8330)
(50, 8340)
(50, 8347)
(50, 8363)
(50, 8365)
(50, 8368)
(50, 8375)
(50, 8395)
(50, 8424)
(50, 8426)
(50, 8433)
(50, 8437)
(50, 8441)
(50, 8457)
(50, 8485)
(50, 8488)
(50, 8490)
(50, 8508)
(50, 8517)
(50, 8533)
(50, 8535)
(50, 8547)
(50, 8565)
(50, 8569)
(50, 8582)
(50, 8589)
(50, 8601)
(50, 8640)
(50, 8667)
(50, 8689)
(50, 8693)
(50, 8695)
(50, 8701)
(50, 8715)
(50, 8719)
(50, 8725)
(50, 8729)
(50, 8742)
(50, 8753)
(50, 8761)
(50, 8809)
(50, 8840)
(50, 8852)
(50, 8854)
(50, 8860)
(50, 8861)
(50, 8865)
(50, 8870)
(50, 8878)
(50, 8881)
(50, 8895)
(50, 8898)
(50, 8906)
(50, 8930)
(50, 8957)
(50, 8962)
(50, 8966)
(50, 8978)
(50, 8997)
(50, 9023)
(50, 9041)
(50, 9044)
(50, 9045)
(50, 9054)
(50, 9088)
(50, 9091)
(50, 9117)
(50, 9123)
(50, 9124)
(50, 9129)
(50, 9139)
(50, 9154)
(50, 9176)
(50, 9182)
(50, 9188)
(50, 9208)
(50, 9225)
(50, 9232)
(50, 9233)
(50, 9243)
(50, 9246)
(50, 9254)
(50, 9255)
(50, 9285)
(50, 9286)
(50, 9295)
(50, 9298)
(50, 9304)
(50, 9315)
(50, 9336)
(50, 9375)
(50, 9386)
(50, 9403)
(50, 9409)
(50, 9421)
(50, 9423)
(50, 9424)
(50, 9429)
(50, 9430)
(50, 9439)
(50, 9446)
(50, 9469)
(50, 9487)
(50, 9492)
(50, 9519)
(50, 9531)
(50, 9533)
(50, 9538)
(50, 9563)
(50, 9566)
(50, 9595)
(50, 9596)
(50, 9601)
(50, 9604)
(50, 9612)
(50, 9627)
(50, 9630)
(50, 9636)
(50, 9656)
(50, 9670)
(50, 9686)
(50, 9687)
(50, 9698)
(50, 9723)
(50, 9726)
(50, 9746)
(50, 9765)
(50, 9783)
(50, 9805)
(50, 9815)
(50, 9862)
(50, 9878)
(50, 9980)
(50, 9984)
(50, 9996)
(50, 9998)
(50, 10030)
(50, 10043)
(50, 10052)
(50, 10078)
(50, 10083)
(50, 10099)
(50, 10110)
(50, 10117)
(50, 10132)
(50, 10144)
(50, 10149)
(50, 10153)
(50, 10167)
(50, 10170)
(50, 10172)
(50, 10178)
(50, 10198)
(50, 10211)
(50, 10223)
(50, 10233)
(50, 10246)
(50, 10247)
(50, 10253)
(50, 10261)
(50, 10266)
(50, 10269)
(50, 10272)
(50, 10302)
(50, 10334)
(50, 10350)
(50, 10407)
(50, 10419)
(50, 10424)
(50, 10425)
(50, 10435)
(50, 10438)
(50, 10445)
(50, 10449)
(50, 10456)
(50, 10471)
(50, 10497)
(50, 10501)
(50, 10511)
(50, 10515)
(50, 10536)
(50, 10546)
(50, 10570)
(50, 10587)
(50, 10591)
(50, 10593)
(50, 10597)
(50, 10605)
(50, 10613)
(50, 10630)
(50, 10658)
(50, 10680)
(50, 10713)
(50, 10740)
(50, 10752)
(50, 10776)
(50, 10778)
(50, 10811)
(50, 10834)
(50, 10841)
(50, 10866)
(50, 10881)
(50, 10914)
(50, 10925)
(50, 10939)
(50, 10942)
(50, 10954)
(50, 10957)
(50, 10959)
(50, 10963)
(50, 10972)
(50, 10976)
(50, 10995)
(50, 10998)
(50, 11000)
(50, 11008)
(50, 11048)
(50, 11055)
(50, 11066)
(50, 11096)
(50, 11113)
(50, 11119)
(50, 11151)
(50, 11154)
(50, 11155)
(50, 11173)
(50, 11200)
(50, 11203)
(50, 11211)
(50, 11233)
(50, 11258)
(50, 11267)
(50, 11291)
(50, 11299)
(50, 11308)
(50, 11310)
(50, 11341)
(50, 11387)
(50, 11391)
(50, 11406)
(50, 11413)
(50, 11451)
(50, 11508)
(50, 11526)
(50, 11531)
(50, 11539)
(50, 11545)
(50, 11549)
(50, 11561)
(50, 11572)
(50, 11581)
(50, 11586)
(50, 11591)
(50, 11604)
(50, 11629)
(50, 11638)
(50, 11668)
(50, 11670)
(50, 11677)
(50, 11687)
(50, 11699)
(50, 11717)
(50, 11753)
(50, 11757)
(50, 11782)
(50, 11800)
(50, 11817)
(50, 11834)
(50, 11937)
(50, 11943)
(50, 11947)
(50, 11982)
(50, 11988)
(50, 12010)
(50, 12072)
(50, 12084)
(50, 12087)
(50, 12093)
(50, 12150)
(50, 12161)
(50, 12167)
(50, 12171)
(50, 12191)
(50, 12197)
(50, 12226)
(50, 12236)
(50, 12243)
(50, 12245)
(50, 12250)
(50, 12330)
(50, 12332)
(50, 12363)
(50, 12389)
(50, 12394)
(50, 12401)
(50, 12402)
(50, 12439)
(50, 12441)
(50, 12453)
(50, 12460)
(50, 12487)
(50, 12503)
(50, 12534)
(50, 12551)
(50, 12582)
(50, 12586)
(50, 12613)
(50, 12630)
(50, 12640)
(50, 12651)
(50, 12660)
(50, 12678)
(50, 12690)
(50, 12705)
(50, 12761)
(50, 12765)
(50, 12766)
(50, 12769)
(50, 12786)
(50, 12845)
(50, 12860)
(50, 12865)
(50, 12876)
(50, 12884)
(50, 12887)
(50, 12892)
(50, 12914)
(50, 12929)
(50, 12934)
(50, 12984)
(50, 13001)
(50, 13008)
(50, 13063)
(50, 13131)
(50, 13144)
(50, 13171)
(50, 13228)
(50, 13229)
(50, 13242)
(50, 13249)
(50, 13308)
(50, 13311)
(50, 13324)
(50, 13333)
(50, 13371)
(50, 13376)
(50, 13399)
(50, 13402)
(50, 13435)
(50, 13453)
(50, 13462)
(50, 13477)
(50, 13488)
(50, 13494)
(50, 13502)
(50, 13521)
(50, 13535)
(50, 13544)
(50, 13586)
(50, 13587)
(50, 13592)
(50, 13621)
(50, 13642)
(50, 13664)
(50, 13665)
(50, 13684)
(50, 13696)
(50, 13703)
(50, 13750)
(50, 13763)
(50, 13783)
(50, 13786)
(50, 13789)
(50, 13795)
(50, 13801)
(50, 13815)
(50, 13821)
(50, 13833)
(50, 13843)
(50, 13859)
(50, 13864)
(50, 13870)
(50, 13878)
(50, 13886)
(50, 13900)
(50, 13906)
(50, 13923)
(50, 13927)
(50, 13930)
(50, 13932)
(50, 13937)
(50, 13956)
(50, 13974)
(50, 13977)
(50, 13981)
(50, 13982)
(50, 14003)
(50, 14018)
(50, 14025)
(50, 14034)
(50, 14068)
(50, 14074)
(50, 14075)
(50, 14081)
(50, 14100)
(50, 14112)
(50, 14134)
(50, 14159)
(50, 14182)
(50, 14193)
(50, 14200)
(50, 14202)
(50, 14244)
(50, 14273)
(50, 14330)
(50, 14333)
(50, 14339)
(50, 14348)
(50, 14353)
(50, 14358)
(50, 14398)
(50, 14399)
(50, 14400)
(50, 14445)
(50, 14464)
(50, 14523)
(50, 14553)
(50, 14564)
(50, 14585)
(50, 14586)
(50, 14593)
(50, 14625)
(50, 14642)
(50, 14645)
(50, 14665)
(50, 14666)
(50, 14672)
(50, 14716)
(50, 14740)
(50, 14746)
(50, 14755)
(50, 14761)
(50, 14786)
(50, 14793)
(50, 14799)
(50, 14824)
(50, 14843)
(50, 14845)
(50, 14846)
(50, 14849)
(50, 14867)
(50, 14877)
(50, 14890)
(50, 14899)
(50, 14918)
(50, 14926)
(50, 14928)
(50, 14962)
(50, 14972)
(50, 14973)
(50, 15007)
(50, 15014)
(50, 15020)
(50, 15029)
(50, 15034)
(50, 15054)
(50, 15059)
(50, 15068)
(50, 15173)
(50, 15175)
(50, 15195)
(50, 15205)
(50, 15216)
(50, 15222)
(50, 15226)
(50, 15242)
(50, 15279)
(50, 15313)
(50, 15324)
(50, 15378)
(50, 15387)
(50, 15404)
(50, 15416)
(50, 15429)
(50, 15443)
(50, 15445)
(50, 15457)
(50, 15464)
(50, 15507)
(50, 15533)
(50, 15535)
(50, 15543)
(50, 15566)
(50, 15579)
(50, 15607)
(50, 15625)
(50, 15629)
(50, 15636)
(50, 15657)
(50, 15673)
(50, 15679)
(50, 15717)
(50, 15730)
(50, 15740)
(50, 15760)
(50, 15769)
(50, 15840)
(50, 15853)
(50, 15860)
(50, 15863)
(50, 15864)
(50, 15885)
(50, 15899)
(50, 15903)
(50, 15911)
(50, 15932)
(50, 15935)
(50, 15936)
(50, 15955)
(50, 15987)
(50, 15994)
(50, 16059)
(50, 16083)
(50, 16096)
(50, 16134)
(50, 16157)
(50, 16202)
(50, 16206)
(50, 16212)
(50, 16233)
(50, 16239)
(50, 16243)
(50, 16250)
(50, 16267)
(50, 16274)
(50, 16276)
(50, 16295)
(50, 16303)
(50, 16321)
(50, 16335)
(50, 16346)
(50, 16355)
(50, 16372)
(50, 16383)
(50, 16408)
(50, 16422)
(50, 16427)
(50, 16430)
(50, 16434)
(50, 16489)
(50, 16491)
(50, 16500)
(50, 16512)
(50, 16528)
(50, 16535)
(50, 16557)
(50, 16561)
(50, 16577)
(50, 16583)
(50, 16589)
(50, 16612)
(50, 16622)
(50, 16633)
(50, 16644)
(50, 16653)
(50, 16667)
(50, 16719)
(50, 16729)
(50, 16732)
(50, 16750)
(50, 16760)
(50, 16777)
(50, 16801)
(50, 16825)
(50, 16833)
(50, 16836)
(50, 16843)
(50, 16895)
(50, 16912)
(50, 16921)
(50, 16924)
(50, 16930)
(50, 16939)
(50, 17013)
(50, 17021)
(50, 17022)
(50, 17049)
(50, 17056)
(50, 17058)
(50, 17061)
(50, 17062)
(50, 17096)
(50, 17131)
(50, 17146)
(50, 17148)
(50, 17153)
(50, 17187)
(50, 17195)
(50, 17212)
(50, 17217)
(50, 17240)
(50, 17241)
(50, 17264)
(50, 17286)
(50, 17291)
(50, 17295)
(50, 17302)
(50, 17327)
(50, 17339)
(50, 17392)
(50, 17398)
(50, 17411)
(50, 17415)
(50, 17434)
(50, 17454)
(50, 17457)
(50, 17490)
(50, 17525)
(50, 17526)
(50, 17534)
(50, 17535)
(50, 17541)
(50, 17565)
(50, 17581)
(50, 17601)
(50, 17634)
(50, 17707)
(50, 17764)
(50, 17767)
(50, 17768)
(50, 17786)
(50, 17797)
(50, 17808)
(50, 17809)

(50, 17818)
(50, 17835)
(50, 17853)
(50, 17866)
(50, 17868)
(50, 17869)
(50, 17870)
(50, 17950)
(50, 17959)
(50, 17969)
(50, 17997)
(50, 18021)
(50, 18106)
(50, 18125)
(50, 18129)
(50, 18145)
(50, 18199)
(50, 18212)
(50, 18236)
(50, 18244)
(50, 18251)
(50, 18267)
(50, 18296)
(50, 18306)
(50, 18313)
(50, 18317)
(50, 18343)
(50, 18395)
(50, 18403)
(50, 18411)
(50, 18429)
(50, 18490)
(50, 18499)
(50, 18509)
(50, 18516)
(50, 18538)
(50, 18546)
(50, 18550)
(50, 18570)
(50, 18576)
(50, 18583)
(50, 18607)
(50, 18656)
(50, 18723)
(50, 18728)
(50, 18758)
(50, 18787)
(50, 18815)
(50, 18831)
(50, 18846)
(50, 18914)
(50, 18956)
(50, 18971)
(50, 19019)
(50, 19027)
(50, 19051)
(50, 19056)
(50, 19104)
(50, 19109)
(50, 19126)
(50, 19136)
(50, 19166)
(50, 19198)
(50, 19220)
(50, 19224)
(50, 19263)
(50, 19286)
(50, 19301)
(50, 19338)
(50, 19372)
(50, 19504)
(50, 19564)
(50, 19568)
(50, 19593)
(50, 19614)
(50, 19677)
(50, 19687)
(50, 19719)
(50, 19746)
(50, 19754)
(50, 19807)
(50, 19816)
(50, 19817)
(50, 19820)
(50, 19840)
(50, 19846)
(50, 19848)
(50, 19875)
(50, 19927)
(50, 19956)
(50, 19977)
(50, 19980)
(50, 19985)
(50, 20007)
(50, 20059)
(50, 20069)
(50, 20081)
(50, 20087)
(50, 20097)
(50, 20145)
(50, 20155)
(50, 20166)
(50, 20197)
(50, 20202)
(50, 20234)
(50, 20252)
(50, 20260)
(50, 20267)
(50, 20318)
(50, 20428)
(50, 20449)
(50, 20485)
(50, 20489)
(50, 20497)
(50, 20510)
(50, 20565)
(50, 20574)
(50, 20634)
(50, 20638)
(50, 20640)
(50, 20662)
(50, 20689)
(50, 20725)
(50, 20743)
(50, 20747)
(50, 20764)
(50, 20767)
(50, 20780)
(50, 20802)
(50, 20813)
(50, 20816)
(50, 20822)
(50, 20836)
(50, 20840)
(50, 20866)
(50, 20874)
(50, 20875)
(50, 20880)
(50, 20920)
(50, 20947)
(50, 20952)
(50, 20958)
(50, 20972)
(50, 20978)
(50, 21006)
(50, 21027)
(50, 21056)
(50, 21090)
(50, 21100)
(50, 21118)
(50, 21159)
(50, 21187)
(50, 21218)
(50, 21253)
(50, 21273)
(50, 21282)
(50, 21294)
(50, 21331)
(50, 21356)
(50, 21362)
(50, 21376)
(50, 21378)
(50, 21381)
(50, 21403)
(50, 21419)
(50, 21421)
(50, 21430)
(50, 21452)
(50, 21475)
(50, 21575)
(50, 21603)
(50, 21604)
(50, 21607)
(50, 21623)
(50, 21676)
(50, 21679)
(50, 21699)
(50, 21704)
(50, 21708)
(50, 21717)
(50, 21720)
(50, 21730)
(50, 21757)
(50, 21766)
(50, 21796)
(50, 21853)
(50, 21875)
(50, 21904)
(50, 21906)
(50, 21987)
(50, 21992)
(50, 22083)
(50, 22084)
(50, 22099)
(50, 22102)
(50, 22113)
(50, 22119)
(50, 22134)
(50, 22140)
(50, 22150)
(50, 22185)
(50, 22228)
(50, 22232)
(50, 22248)
(50, 22272)
(50, 22307)
(50, 22309)
(50, 22311)
(50, 22330)
(50, 22346)
(50, 22350)
(50, 22353)
(50, 22363)
(50, 22364)
(50, 22374)
(50, 22381)
(50, 22398)
(50, 22438)
(50, 22535)
(50, 22565)
(50, 22570)
(50, 22578)
(50, 22591)
(50, 22598)
(50, 22609)
(50, 22615)
(50, 22621)
(50, 22623)
(50, 22657)
(50, 22678)
(50, 22683)
(50, 22709)
(50, 22721)
(50, 22802)
(50, 22913)
(50, 22915)
(50, 22935)
(50, 22952)
(50, 22985)
(50, 22995)
(50, 23042)
(50, 23068)
(50, 23083)
(50, 23086)
(50, 23087)
(50, 23158)
(50, 23177)
(50, 23300)
(50, 23316)
(50, 23333)
(50, 23350)
(50, 23356)
(50, 23363)
(50, 23368)
(50, 23370)
(50, 23384)
(50, 23401)
(50, 23421)
(50, 23439)
(50, 23494)
(50, 23498)
(50, 23509)
(50, 23528)
(50, 23530)
(50, 23547)
(50, 23580)
(50, 23584)
(50, 23655)
(50, 23682)
(50, 23687)
(50, 23719)
(50, 23732)
(50, 23746)
(50, 23770)
(50, 23788)
(50, 23796)
(50, 23805)
(50, 23842)
(50, 23956)
(50, 23964)
(50, 24029)
(50, 24042)
(50, 24069)
(50, 24097)
(50, 24098)
(50, 24132)
(50, 24164)
(50, 24181)
(50, 24199)
(50, 24233)
(50, 24254)
(50, 24276)
(50, 24277)
(50, 24286)
(50, 24326)
(50, 24449)
(50, 24475)
(50, 24484)
(50, 24496)
(50, 24505)
(50, 24512)
(50, 24519)
(50, 24552)
(50, 24554)
(50, 24583)
(50, 24629)
(50, 24636)
(50, 24643)
(50, 24662)
(50, 24669)
(50, 24690)
(50, 24696)
(50, 24733)
(50, 24742)
(50, 24748)
(50, 24757)
(50, 24777)
(50, 24802)
(50, 24837)
(50, 24877)
(50, 24895)
(50, 24896)
(50, 24913)
(50, 24939)
(50, 24986)
(50, 25011)
(50, 25095)
(50, 25195)
(50, 25213)
(50, 25241)
(50, 25250)
(50, 25276)
(50, 25348)
(50, 25414)
(50, 25417)
(50, 25434)
(50, 25448)
(50, 25482)
(50, 25520)
(50, 25529)
(50, 25535)
(50, 25540)
(50, 25587)
(50, 25607)
(50, 25691)
(50, 25692)
(50, 25740)
(50, 25746)
(50, 25748)
(50, 25764)
(50, 25833)
(50, 25841)
(50, 25857)
(50, 25887)
(50, 25893)
(50, 25910)
(50, 25949)
(50, 25970)
(50, 25989)
(50, 25992)
(50, 26008)
(50, 26015)
(50, 26026)
(50, 26075)
(50, 26076)
(50, 26097)
(50, 26120)
(50, 26140)
(50, 26151)
(50, 26152)
(50, 26168)
(50, 26171)
(50, 26175)
(50, 26203)
(50, 26233)
(50, 26306)
(50, 26384)
(50, 26405)
(50, 26424)
(50, 26446)
(50, 26470)
(50, 26499)
(50, 26570)
(50, 26604)
(50, 26656)
(50, 26664)
(50, 26790)
(50, 26835)
(50, 26839)
(50, 26890)
(50, 26948)
(50, 26985)
(50, 27038)
(50, 27087)
(50, 27088)
(50, 27115)
(50, 27134)
(50, 27144)
(50, 27153)
(50, 27213)
(50, 27223)
(50, 27227)
(50, 27231)
(50, 27253)
(50, 27281)
(50, 27324)
(50, 27444)
(50, 27446)
(50, 27457)
(50, 27469)
(50, 27471)
(50, 27503)
(50, 27576)
(50, 27636)
(50, 27674)
(50, 27695)
(50, 27703)
(50, 27720)
(50, 27731)
(50, 27769)
(50, 27785)
(50, 27798)
(50, 27815)
(50, 27822)
(50, 27842)
(50, 27979)
(50, 27994)
(50, 28001)
(50, 28046)
(50, 28065)
(50, 28111)
(50, 28120)
(50, 28122)
(50, 28159)
(50, 28205)
(50, 28212)
(50, 28215)
(50, 28237)
(50, 28258)
(50, 28262)
(50, 28264)
(50, 28276)
(50, 28292)
(50, 28298)
(50, 28417)
(50, 28432)
(50, 28452)
(50, 28520)
(50, 28522)
(50, 28525)
(50, 28545)
(50, 28550)
(50, 28567)
(50, 28602)
(50, 28610)
(50, 28669)
(50, 28691)
(50, 28705)
(50, 28709)
(50, 28712)
(50, 28743)
(50, 28744)
(50, 28746)
(50, 28780)
(50, 28781)
(50, 28816)
(50, 28818)
(50, 28836)
(50, 28886)
(50, 28897)
(50, 28933)
(50, 28936)
(50, 28961)
(50, 29030)
(50, 29116)
(50, 29180)
(50, 29211)
(50, 29235)
(50, 29278)
(50, 29380)
(50, 29393)
(50, 29405)
(50, 29431)
(50, 29449)
(50, 29450)
(50, 29485)
(50, 29514)
(50, 29598)
(50, 29600)
(50, 29676)
(50, 29718)
(50, 29750)
(50, 29773)
(50, 29872)
(50, 29957)
(50, 29966)
(50, 29968)
(50, 30042)
(50, 30097)
(50, 30099)
(50, 30104)
(50, 30233)
(50, 30305)
(50, 30464)
(50, 30617)
(50, 30676)
(50, 30768)
(50, 30776)
(50, 30926)
(50, 30934)
(50, 30952)
(50, 31137)
(50, 31227)
(50, 31255)
(50, 31275)
(50, 31313)
(50, 31364)
(50, 31448)
(50, 31499)
(50, 31594)
(50, 31600)
(50, 31648)
(50, 31704)
(50, 31807)
(50, 31809)
(50, 31848)
(50, 31861)
(50, 31883)
(50, 31946)
(50, 31953)
(50, 31965)
(50, 32024)
(50, 32058)
(50, 32061)
(50, 32062)
(50, 32202)
(50, 32208)
(50, 32213)
(50, 32237)
(50, 32297)
(50, 32317)
(50, 32330)
(50, 32334)
(50, 32353)
(50, 32420)
(50, 32428)
(50, 32504)
(50, 32513)
(50, 32588)
(50, 32612)
(50, 32618)
(50, 32694)
(50, 32727)
(50, 32735)
(50, 32749)
(50, 32787)
(50, 32808)
(50, 32819)
(50, 32856)
(50, 32888)
(50, 32899)
(50, 32923)
(50, 32937)
(50, 32957)
(50, 33055)
(50, 33062)
(50, 33066)
(50, 33090)
(50, 33107)
(50, 33118)
(50, 33140)
(50, 33148)
(50, 33151)
(50, 33153)
(50, 33164)
(50, 33165)
(50, 33198)
(50, 33224)
(50, 33225)
(50, 33292)
(50, 33309)
(50, 33361)
(50, 33381)
(50, 33387)
(50, 33410)
(50, 33476)
(50, 33478)
(50, 33481)
(50, 33503)
(50, 33520)
(50, 33690)
(50, 33704)
(50, 33718)
(50, 33848)
(50, 33915)
(50, 33920)
(50, 33922)
(50, 33984)
(50, 34145)
(50, 34185)
(50, 34200)
(50, 34215)
(50, 34242)
(50, 34273)
(50, 34339)
(50, 34362)
(50, 34387)
(50, 34423)
(50, 34457)
(50, 34499)
(50, 34506)
(50, 34684)
(50, 34690)
(50, 34707)
(50, 34800)
(50, 34827)
(50, 34862)
(50, 34869)
(50, 34872)
(50, 34876)
(50, 34895)
(50, 34971)
(50, 34978)
(50, 35012)
(50, 35021)
(50, 35089)
(50, 35096)
(50, 35161)
(50, 35190)
(50, 35251)
(50, 35270)
(50, 35293)
(50, 35386)
(50, 35471)
(50, 35480)
(50, 35547)
(50, 35571)
(50, 35597)
(50, 35613)
(50, 35625)
(50, 35637)
(50, 35654)
(50, 35662)
(50, 35710)
(50, 35725)
(50, 35862)
(50, 35897)
(50, 35998)
(50, 36009)
(50, 36031)
(50, 36058)
(50, 36157)
(50, 36202)
(50, 36241)
(50, 36273)
(50, 36288)
(50, 36299)
(50, 36311)
(50, 36312)
(50, 36324)
(50, 36531)
(50, 36576)
(50, 36628)
(50, 36647)
(50, 36651)
(50, 36691)
(50, 36702)
(50, 36743)
(50, 36776)
(50, 36821)
(50, 36842)
(50, 36858)
(50, 36901)
(50, 36903)
(50, 36910)
(50, 36970)
(50, 36989)
(50, 37039)
(50, 37057)
(50, 37069)
(50, 37121)
(50, 37124)
(50, 37125)
(50, 37128)
(50, 37144)
(50, 37191)
(50, 37198)
(50, 37220)
(50, 37244)
(50, 37492)
(50, 37508)
(50, 37536)
(50, 37575)
(50, 37642)
(50, 37660)
(50, 37762)
(50, 37765)
(50, 37782)
(50, 37816)
(50, 37821)
(50, 37890)
(50, 37963)
(50, 38013)
(50, 38066)
(50, 38091)
(50, 38106)
(50, 38124)
(50, 38319)
(50, 38335)
(50, 38406)
(50, 38413)
(50, 38431)
(50, 38437)
(50, 38440)
(50, 38451)
(50, 38520)
(50, 38634)
(50, 38664)
(50, 38686)
(50, 38786)
(50, 38827)
(50, 38892)
(50, 38950)
(50, 38966)
(50, 39037)
(50, 39105)
(50, 39134)
(50, 39140)
(50, 39163)
(50, 39191)
(50, 39238)
(50, 39265)
(50, 39309)
(50, 39364)
(50, 39370)
(50, 39437)
(50, 39451)
(50, 39464)
(50, 39561)
(50, 39566)
(50, 39628)
(50, 39702)
(50, 39736)
(50, 39839)
(50, 39988)
(50, 39996)
(50, 40069)
(50, 40087)
(50, 40097)
(50, 40118)
(50, 40123)
(50, 40212)
(50, 40246)
(50, 40271)
(50, 40325)
(50, 40400)
(50, 40404)
(50, 40648)
(50, 40661)
(50, 40716)
(50, 40801)
(50, 40814)
(50, 40838)
(50, 40877)
(50, 40915)
(50, 41019)
(50, 41052)
(50, 41120)
(50, 41207)
(50, 41240)
(50, 41259)
(50, 41276)
(50, 41280)
(50, 41428)
(50, 41452)
(50, 41475)
(50, 41487)
(50, 41513)
(50, 41551)
(50, 41616)
(50, 41639)
(50, 41749)
(50, 41815)
(50, 41848)
(50, 41869)
(50, 41889)
(50, 41949)
(50, 41964)
(50, 41981)
(50, 41993)
(50, 42040)
(50, 42073)
(50, 42074)
(50, 42090)
(50, 42155)
(50, 42173)
(50, 42201)
(50, 42223)
(50, 42239)
(50, 42270)
(50, 42356)
(50, 42366)
(50, 42376)
(50, 42391)
(50, 42416)
(50, 42476)
(50, 42481)
(50, 42698)
(50, 42745)
(50, 42750)
(50, 42794)
(50, 42798)
(50, 42883)
(50, 42918)
(50, 43041)
(50, 43055)
(50, 43114)
(50, 43205)
(50, 43356)
(50, 43435)
(50, 43437)
(50, 43450)
(50, 43462)
(50, 43475)
(50, 43531)
(50, 43589)
(50, 43643)
(50, 43742)
(50, 43784)
(50, 43806)
(50, 43820)
(50, 43857)
(50, 43929)
(50, 43946)
(50, 44002)
(50, 44151)
(50, 44159)
(50, 44205)
(50, 44332)
(50, 44436)
(50, 44442)
(50, 44443)
(50, 44513)
(50, 44519)
(50, 44673)
(50, 44720)
(50, 44776)
(50, 44828)
(50, 44846)
(50, 44900)
(50, 44911)
(50, 44947)
(50, 44996)
(50, 45048)
(50, 45058)
(50, 45078)
(50, 45156)
(50, 45200)
(50, 45248)
(50, 45413)
(50, 45422)
(50, 45498)
(50, 45578)
(50, 45607)
(50, 45720)
(50, 45837)
(50, 45858)
(50, 45870)
(50, 45913)
(50, 45924)
(50, 45949)
(50, 45969)
(50, 46006)
(50, 46034)
(50, 46039)
(50, 46102)
(50, 46133)
(50, 46134)
(50, 46163)
(50, 46183)
(50, 46225)
(50, 46250)
(50, 46389)
(50, 46480)
(50, 46562)
(50, 46639)
(50, 46682)
(50, 46688)
(50, 46689)
(50, 46734)
(50, 46735)
(50, 46824)
(50, 46920)
(50, 46952)
(50, 46987)
(50, 46997)
(50, 47051)
(50, 47168)
(50, 47173)
(50, 47351)
(50, 47401)
(50, 47420)
(50, 47472)
(50, 47536)
(50, 47557)
(50, 47671)
(50, 47711)
(50, 47735)
(50, 47746)
(50, 47759)
(50, 47765)
(50, 47798)
(50, 47818)
(50, 47980)
(50, 48376)
(50, 48434)
(50, 48460)
(50, 48556)
(50, 48586)
(50, 48773)
(50, 48818)
(50, 48879)
(50, 48914)
(50, 48946)
(50, 48971)
(50, 49116)
(50, 49221)
(50, 49285)
(50, 49336)
(50, 49351)
(50, 49423)
(50, 49462)
(50, 49542)
(50, 49625)
(50, 49666)
(50, 49683)
(50, 49746)
(50, 49762)
(50, 49793)
(50, 49875)
(50, 49948)
(50, 49975)
(50, 50047)
(50, 50063)
(50, 50219)
(50, 50251)
(50, 50384)
(50, 50477)
(50, 50486)
(50, 50513)
(50, 50845)
(50, 50902)
(50, 50976)
(50, 51079)
(50, 51125)
(50, 51137)
(50, 51182)
(50, 51208)
(50, 51334)
(50, 51407)
(50, 51454)
(50, 51461)
(50, 51599)
(50, 51675)
(50, 51980)
(50, 52160)
(50, 52197)
(50, 52217)
(50, 52228)
(50, 52250)
(50, 52266)
(50, 52274)
(50, 52293)
(50, 52300)
(50, 52334)
(50, 52410)
(50, 52431)
(50, 52566)
(50, 52579)
(50, 52595)
(50, 52780)
(50, 52796)
(50, 52822)
(50, 52919)
(50, 52947)
(50, 52959)
(50, 53139)
(50, 53227)
(50, 53330)
(50, 53497)
(50, 53498)
(50, 53597)
(50, 53829)
(50, 53873)
(50, 53887)
(50, 54151)
(50, 54165)
(50, 54181)
(50, 54258)
(50, 54418)
(50, 54428)
(50, 54571)
(50, 54635)
(50, 54650)
(50, 54691)
(50, 54842)
(50, 54876)
(50, 54984)
(50, 55043)
(50, 55186)
(50, 55269)
(50, 55274)
(50, 55342)
(50, 55365)
(50, 55400)
(50, 55486)
(50, 55531)
(50, 55606)
(50, 55658)
(50, 55698)
(50, 55729)
(50, 55834)
(50, 55889)
(50, 56053)
(50, 56159)
(50, 56389)
(50, 56418)
(50, 56552)
(50, 56640)
(50, 56670)
(50, 56745)
(50, 56833)
(50, 57303)
(50, 57322)
(50, 57369)
(50, 57424)
(50, 57833)
(50, 57866)
(50, 57999)
(50, 58098)
(50, 58114)
(50, 58218)
(50, 58458)
(50, 58498)
(50, 58505)
(50, 58607)
(50, 58781)
(50, 58849)
(50, 58999)
(50, 59036)
(50, 59127)
(50, 59173)
(50, 59495)
(50, 59534)
(50, 59626)
(50, 59689)
(50, 59779)
(50, 59916)
(50, 60079)
(50, 60088)
(50, 60158)
(50, 60218)
(50, 60316)
(50, 60485)
(50, 60580)
(50, 60585)
(50, 60619)
(50, 60699)
(50, 60921)
(50, 60944)
(50, 60968)
(50, 61081)
(50, 61295)
(50, 61642)
(50, 61675)
(50, 61697)
(50, 61754)
(50, 61773)
(50, 61778)
(50, 61948)
(50, 61976)
(50, 62259)
(50, 62264)
(50, 62415)
(50, 62450)
(50, 62500)
(50, 62544)
(50, 62622)
(50, 63043)
(50, 63063)
(50, 63096)
(50, 63216)
(50, 63342)
(50, 63395)
(50, 63431)
(50, 63453)
(50, 63463)
(50, 63505)
(50, 63506)
(50, 63797)
(50, 63905)
(50, 63942)
(50, 64013)
(50, 64073)
(50, 64142)
(50, 64511)
(50, 64519)
(50, 64524)
(50, 64665)
(50, 64727)
(50, 64757)
(50, 64804)
(50, 65024)
(50, 65203)
(50, 65249)
(50, 65359)
(50, 65393)
(50, 65464)
(50, 65565)
(50, 65631)
(50, 65645)
(50, 65707)
(50, 65880)
(50, 66083)
(50, 66135)
(50, 66283)
(50, 66357)
(50, 66380)
(50, 66469)
(50, 66501)
(50, 66537)
(50, 66861)
(50, 67009)
(50, 67023)
(50, 67044)
(50, 67077)
(50, 67091)
(50, 67103)
(50, 67295)
(50, 67531)
(50, 67761)
(50, 67810)
(50, 67861)
(50, 68356)
(50, 68676)
(50, 68681)
(50, 68756)
(50, 68831)
(50, 68894)
(50, 68917)
(50, 68941)
(50, 69099)
(50, 69340)
(50, 69367)
(50, 69442)
(50, 69661)
(50, 69709)
(50, 69967)
(50, 70002)
(50, 70019)
(50, 70061)
(50, 70217)
(50, 70311)
(50, 70400)
(50, 70648)
(50, 70990)
(50, 71109)

(50, 71115)
(50, 71372)
(50, 71404)
(50, 71492)
(50, 71518)
(50, 71870)
(50, 72155)
(50, 72321)
(50, 72453)
(50, 72797)
(50, 73085)
(50, 73090)
(50, 73240)
(50, 73314)
(50, 73442)
(50, 73673)
(50, 73750)
(50, 73955)
(50, 74171)
(50, 74273)
(50, 74319)
(50, 74364)
(50, 74578)
(50, 74749)
(50, 74782)
(50, 74934)
(50, 75087)
(50, 75129)
(50, 75382)
(50, 75388)
(50, 75403)
(50, 75450)
(50, 75455)
(50, 75568)
(50, 75643)
(50, 75674)
(50, 75889)
(50, 75990)
(50, 76227)
(50, 76258)
(50, 76314)
(50, 76569)
(50, 76652)
(50, 76794)
(50, 77076)
(50, 77079)
(50, 77117)
(50, 77230)
(50, 77350)
(50, 77358)
(50, 77422)
(50, 77435)
(50, 77547)
(50, 77742)
(50, 78064)
(50, 78163)
(50, 78265)
(50, 78305)
(50, 78337)
(50, 78506)
(50, 78532)
(50, 78859)
(50, 79303)
(50, 79499)
(50, 79626)
(50, 80026)
(50, 80261)
(50, 80317)
(50, 80406)
(50, 80956)
(50, 81234)
(50, 81308)
(50, 81327)
(50, 81442)
(50, 81625)
(50, 81642)
(50, 81837)
(50, 82128)
(50, 82291)
(50, 82713)
(50, 82752)
(50, 82782)
(50, 82839)
(50, 82888)
(50, 82910)
(50, 82916)
(50, 83029)
(50, 83384)
(50, 83593)
(50, 83629)
(50, 83686)
(50, 83768)
(50, 84345)
(50, 84585)
(50, 85215)
(50, 85579)
(50, 86074)
(50, 86129)
(50, 86395)
(50, 86771)
(50, 86793)
(50, 86905)
(50, 86956)
(50, 86986)
(50, 87841)
(50, 88247)
(50, 88319)
(50, 88499)
(50, 88737)
(50, 88759)
(50, 88765)
(50, 88830)
(50, 88880)
(50, 88995)
(50, 89118)
(50, 89120)
(50, 89201)
(50, 89322)
(50, 89513)
(50, 89542)
(50, 89889)
(50, 90336)
(50, 90912)
(50, 90928)
(50, 91042)
(50, 91108)
(50, 91738)
(50, 92376)
(50, 92501)
(50, 92565)
(50, 92582)
(50, 92709)
(50, 93019)
(50, 93158)
(50, 93389)
(50, 93420)
(50, 93643)
(50, 93653)
(50, 93772)
(50, 94392)
(50, 94528)
(50, 94565)
(50, 94737)
(50, 95203)
(50, 95535)
(50, 95696)
(50, 95840)
(50, 96024)
(50, 96189)
(50, 96317)
(50, 96318)
(50, 96319)
(50, 96443)
(50, 96656)
(50, 97032)
(50, 97265)
(50, 97581)
(50, 98078)
(50, 98294)
(50, 98733)
(50, 98736)
(50, 98764)
(50, 98786)
(50, 98963)
(50, 98970)
(50, 98990)
(50, 99193)
(50, 99478)
(50, 99710)
(50, 99863)
(50, 99892)
(50, 99958)
(50, 100157)
(50, 100948)
(50, 101108)
(50, 101407)
(50, 101492)
(50, 101497)
(50, 101547)
(50, 101564)
(50, 101633)
(50, 102172)
(50, 102228)
(50, 102410)
(50, 102506)
(50, 102599)
(50, 103350)
(50, 103505)
(50, 104169)
(50, 104234)
(50, 104430)
(50, 105151)
(50, 105160)
(50, 105543)
(50, 106331)
(50, 106567)
(50, 106740)
(50, 107118)
(50, 107215)
(50, 107431)
(50, 107449)
(50, 107456)
(50, 107667)
(50, 107702)
(50, 107759)
(50, 107771)
(50, 107841)
(50, 107848)
(50, 107931)
(50, 108472)
(50, 108692)
(50, 109233)
(50, 109299)
(50, 110224)
(50, 110232)
(50, 110527)
(50, 110768)
(50, 110826)
(50, 111408)
(50, 111467)
(50, 111860)
(50, 111944)
(50, 112656)
(50, 113237)
(50, 113449)
(50, 113792)
(50, 113924)
(50, 113993)
(50, 114520)
(50, 114638)
(50, 114678)
(50, 114736)
(50, 115507)
(50, 115541)
(50, 116111)
(50, 116229)
(50, 116638)
(50, 116672)
(50, 116714)
(50, 116901)
(50, 116927)
(50, 116979)
(50, 117404)
(50, 117671)
(50, 118428)
(50, 118572)
(50, 118811)
(50, 119224)
(50, 119490)
(50, 120725)
(50, 120877)
(50, 121073)
(50, 121097)
(50, 121730)
(50, 122109)
(50, 122151)
(50, 122397)
(50, 122623)
(50, 122979)
(50, 123010)
(50, 123143)
(50, 124053)
(50, 124098)
(50, 124475)
(50, 124700)
(50, 125488)
(50, 125744)
(50, 126979)
(50, 127089)
(50, 127317)
(50, 128026)
(50, 128349)
(50, 128961)
(50, 129928)
(50, 130044)
(50, 130882)
(50, 131090)
(50, 131219)
(50, 131346)
(50, 131500)
(50, 131506)
(50, 131533)
(50, 131561)
(50, 131613)
(50, 131636)
(50, 131887)
(50, 132403)
(50, 133568)
(50, 133801)
(50, 134063)
(50, 134168)
(50, 134421)
(50, 134623)
(50, 134905)
(50, 135394)
(50, 136146)
(50, 136484)
(50, 136555)
(50, 136606)
(50, 136872)
(50, 136885)
(50, 137130)
(50, 137436)
(50, 137974)
(50, 138028)
(50, 138115)
(50, 138333)
(50, 138428)
(50, 138494)
(50, 139654)
(50, 139668)
(50, 139900)
(50, 139966)
(50, 140247)
(50, 141236)
(50, 141617)
(50, 141752)
(50, 142324)
(50, 143679)
(50, 144170)
(50, 144248)
(50, 145448)
(50, 146156)
(50, 146318)
(50, 146445)
(50, 146551)
(50, 146723)
(50, 147430)
(50, 147546)
(50, 147972)
(50, 148289)
(50, 149265)
(50, 149610)
(50, 149618)
(50, 149778)
(50, 150642)
(50, 150865)
(50, 150934)
(50, 151131)
(50, 151372)
(50, 152021)
(50, 152691)
(50, 152982)
(50, 153720)
(50, 153923)
(50, 153990)
(50, 154358)
(50, 154727)
(50, 154834)
(50, 155547)
(50, 156545)
(50, 156813)
(50, 156823)
(50, 156898)
(50, 157107)
(50, 157505)
(50, 157733)
(50, 158080)
(50, 158840)
(50, 159063)
(50, 159429)
(50, 159437)
(50, 159720)
(50, 159978)
(50, 160099)
(50, 160248)
(50, 160331)
(50, 160645)
(50, 161252)
(50, 161419)
(50, 161573)
(50, 162233)
(50, 162310)
(50, 162642)
(50, 162878)
(50, 163040)
(50, 164343)
(50, 165224)
(50, 165676)
(50, 166158)
(50, 166426)
(50, 166492)
(50, 166994)
(50, 167134)
(50, 168148)
(50, 168852)
(50, 168878)
(50, 169468)
(50, 169572)
(50, 169842)
(50, 170539)
(50, 172188)
(50, 172331)
(50, 172332)
(50, 172778)
(50, 172780)
(50, 174214)
(50, 174528)
(50, 175177)
(50, 175511)
(50, 176695)
(50, 177223)
(50, 177772)
(50, 177843)
(50, 177934)
(50, 178011)
(50, 179684)
(50, 179703)
(50, 180719)
(50, 180822)
(50, 180967)
(50, 181058)
(50, 182265)
(50, 182493)
(50, 183182)
(50, 183862)
(50, 185079)
(50, 186494)
(50, 187105)
(50, 187126)
(50, 188923)
(50, 189885)
(50, 189927)
(50, 190039)
(50, 190865)
(50, 192768)
(50, 193063)
(50, 194656)
(50, 194851)
(50, 195085)
(50, 195408)
(50, 195751)
(50, 197131)
(50, 197145)
(50, 197363)
(50, 197465)
(50, 197559)
(50, 200169)
(50, 200186)
(50, 200226)
(50, 200549)
(50, 200600)
(50, 200849)
(50, 201081)
(50, 201140)
(50, 201292)
(50, 202667)
(50, 203065)
(50, 203206)
(50, 203922)
(50, 204214)
(50, 206086)
(50, 207627)
(50, 207820)
(50, 209233)
(50, 209714)
(50, 210312)
(50, 211033)
(50, 211226)
(50, 212693)
(50, 214346)
(50, 214437)
(50, 215888)
(50, 216469)
(50, 218733)
(50, 219607)
(50, 220000)
(50, 221339)
(50, 221578)
(50, 221939)
(50, 222209)
(50, 226073)
(50, 229363)
(50, 230041)
(50, 231236)
(50, 233385)
(50, 233740)
(50, 234878)
(50, 234906)
(50, 235406)
(50, 238136)
(50, 238318)
(50, 238823)
(50, 242803)
(50, 243231)
(50, 244826)
(50, 245285)
(50, 247336)
(50, 248007)
(50, 250304)
(50, 250331)
(50, 251133)
(50, 252264)
(50, 252273)
(50, 252409)
(50, 252825)
(50, 254969)
(50, 255755)
(50, 255793)
(50, 259424)
(50, 262382)
(50, 262391)
(50, 262604)
(50, 263801)
(50, 265128)
(50, 266931)
(50, 267587)
(50, 268100)
(50, 268685)
(50, 269282)
(50, 269291)
(50, 269637)
(50, 270056)
(50, 274055)
(50, 274549)
(50, 274569)
(50, 275174)
(50, 275487)
(50, 277789)
(50, 278831)
(50, 280566)
(50, 280895)
(50, 281674)
(50, 284307)
(50, 285407)
(50, 285465)
(50, 287085)
(50, 288288)
(50, 291309)
(50, 291826)
(50, 294567)
(50, 295223)
(50, 295266)
(50, 295803)
(50, 297052)
(50, 297488)
(50, 297619)
(50, 297735)
(50, 299630)
(50, 301356)
(50, 304204)
(50, 306479)
(50, 306935)
(50, 308760)
(50, 310235)
(50, 311687)
(50, 312311)
(50, 313166)
(50, 315335)
(50, 316236)
(50, 319294)
(50, 319431)
(50, 320918)
(50, 321520)
(50, 322833)
(50, 323444)
(50, 330844)
(50, 331298)
(50, 334811)
(50, 336463)
(50, 340223)
(50, 343829)
(50, 344791)
(50, 348432)
(50, 349497)
(50, 350209)
(50, 350670)
(50, 351715)
(50, 355329)
(50, 360485)
(50, 365169)
(50, 366513)
(50, 368130)
(50, 372813)
(50, 375586)
(50, 375770)
(50, 375992)
(50, 379448)
(50, 382748)
(50, 384504)
(50, 389891)
(50, 392365)
(50, 398552)
(50, 400721)
(50, 402002)
(50, 406220)
(50, 411442)
(50, 412992)
(50, 413344)
(50, 415057)
(50, 421407)
(50, 422679)
(50, 422718)
(50, 423895)
(50, 425363)
(50, 425790)
(50, 430640)
(50, 432226)
(50, 432552)
(50, 434972)
(50, 437994)
(50, 440171)
(50, 441603)
(50, 441815)
(50, 442179)
(50, 448734)
(50, 451225)
(50, 455746)
(50, 463490)
(50, 464697)
(50, 467026)
(50, 468730)
(50, 471221)
(50, 483878)
(50, 488073)
(50, 488406)
(50, 492276)
(50, 494593)
(50, 494919)
(50, 496005)
(50, 498365)
(50, 498886)
(50, 501226)
(50, 508640)
(50, 513657)
(50, 514453)
(50, 515269)
(50, 516564)
(50, 517110)
(50, 519445)
(50, 529710)
(50, 534543)
(50, 535153)
(50, 536499)
(50, 537656)
(50, 538479)
(50, 541781)
(50, 543376)
(50, 544179)
(50, 548285)
(50, 558979)
(50, 572003)
(50, 576567)
(50, 585375)
(50, 600158)
(50, 601723)
(50, 602095)
(50, 602622)
(50, 603403)
(50, 618754)
(50, 620961)
(50, 622263)
(50, 625249)
(50, 626667)
(50, 626681)
(50, 630380)
(50, 634266)
(50, 658466)
(50, 662564)
(50, 662614)
(50, 670850)
(50, 674158)
(50, 677560)
(50, 685306)
(50, 688078)
(50, 691893)
(50, 703462)
(50, 713335)
(50, 718451)
(50, 718633)
(50, 722023)
(50, 735334)
(50, 741096)
(50, 743159)
(50, 744344)
(50, 774769)
(50, 782341)
(50, 783969)
(50, 795225)
(50, 798552)
(50, 799874)
(50, 800647)
(50, 802374)
(50, 805029)
(50, 805235)
(50, 805321)
(50, 809858)
(50, 823318)
(50, 839631)
(50, 840978)
(50, 862477)
(50, 863420)
(50, 864263)
(50, 894014)
(50, 900993)
(50, 903393)
(50, 905116)
(50, 916542)
(50, 916829)
(50, 916924)
(50, 919040)
(50, 919628)
(50, 920581)
(50, 927644)
(50, 930450)
(50, 947735)
(50, 949113)
(50, 953207)
(50, 971777)
(50, 980263)
(50, 998954)
(50, 1024266)
(50, 1029655)
(50, 1049025)
(50, 1081726)
(50, 1145956)
(50, 1152425)
(50, 1163414)
(50, 1202362)
(50, 1223348)
(50, 1229226)
(50, 1280122)
(50, 1320134)
(50, 1339532)
(50, 1385108)
(50, 1418788)
(50, 1493350)
(50, 1503085)
(50, 1510271)
(50, 1526006)
(50, 1585873)
(50, 1714773)
(50, 1748066)
(50, 1781642)
(50, 1809034)
(50, 1820584)
(50, 1931249)
(50, 1951269)
(50, 2035210)
(50, 2189641)
(50, 2230722)
(50, 2368139)
(50, 2496435)
(50, 2504700)
(50, 3010232)
(50, 3095313)
(50, 3817117)
(50, 4092459)
(50, 5194675)
(50, 9818605)

# Applying

The pandas developers have three broad categories of data processing to happen during the apply step, Aggregation of group data, Transformation of group data, and Filtration of group data

## Aggregation

In [11]:
df = pd.read_csv('census.csv')
df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861

In [12]:
print((df['SUMLEV'].unique()))

[40 50]

In [13]:
# The most straight forward apply step is the aggregation of data, and uses the method agg() on the groupby
# object. Thus far we have only iterated through the groupby object, unpacking it into a label (the group
# name) and a dataframe. But with agg we can pass in a dictionary of the columns we are interested in
# aggregating along with the function we are looking to apply to aggregate.

df.groupby("STNAME").agg({"SUMLEV":np.average})

                         SUMLEV
STNAME
Alabama               49.852941
Alaska                49.666667
Arizona               49.375000
Arkansas              49.868421
California            49.830508
Colorado              49.846154
Connecticut           48.888889
Delaware              47.500000
District of Columbia  45.000000
Florida               49.852941
Georgia               49.937500
Hawaii                48.333333
Idaho                 49.777778
Illinois              49.902913
Indiana               49.892473
Iowa                  49.900000
Kansas                49.905660
Kentucky              49.917355
Louisiana             49.846154
Maine                 49.411765
Maryland              49.600000
Massachusetts         49.333333
Michigan              49.880952
Minnesota             49.886364
Mississippi           49.879518
Missouri              49.913793
Montana               49.824561
Nebraska              49.893617
Nevada                49.444444
New Hampshire         49.090909
New Jersey            49.545455
New Mexico            49.705882
New York              49.841270
North Carolina        49.900990
North Dakota          49.814815
Ohio                  49.887640
Oklahoma              49.871795
Oregon                49.729730
Pennsylvania          49.852941
Rhode Island          48.333333
South Carolina        49.787234
South Dakota          49.850746
Tennessee             49.895833
Texas                 49.960784
Utah                  49.666667
Vermont               49.333333
Virginia              49.925373
Washington            49.750000
West Virginia         49.821429
Wisconsin             49.863014
Wyoming               49.583333

In [14]:
df.groupby("STNAME").agg({"SUMLEV":np.nanmean})

                         SUMLEV
STNAME
Alabama               49.852941
Alaska                49.666667
Arizona               49.375000
Arkansas              49.868421
California            49.830508
Colorado              49.846154
Connecticut           48.888889
Delaware              47.500000
District of Columbia  45.000000
Florida               49.852941
Georgia               49.937500
Hawaii                48.333333
Idaho                 49.777778
Illinois              49.902913
Indiana               49.892473
Iowa                  49.900000
Kansas                49.905660
Kentucky              49.917355
Louisiana             49.846154
Maine                 49.411765
Maryland              49.600000
Massachusetts         49.333333
Michigan              49.880952
Minnesota             49.886364
Mississippi           49.879518
Missouri              49.913793
Montana               49.824561
Nebraska              49.893617
Nevada                49.444444
New Hampshire         49.090909
New Jersey            49.545455
New Mexico            49.705882
New York              49.841270
North Carolina        49.900990
North Dakota          49.814815
Ohio                  49.887640
Oklahoma              49.871795
Oregon                49.729730
Pennsylvania          49.852941
Rhode Island          48.333333
South Carolina        49.787234
South Dakota          49.850746
Tennessee             49.895833
Texas                 49.960784
Utah                  49.666667
Vermont               49.333333
Virginia              49.925373
Washington            49.750000
West Virginia         49.821429
Wisconsin             49.863014
Wyoming               49.583333

In [15]:
df.groupby("STNAME").agg({"SUMLEV":(np.nanmean, np.std)})

                         SUMLEV
                        nanmean       std
STNAME
Alabama               49.852941  1.212678
Alaska                49.666667  1.825742
Arizona               49.375000  2.500000
Arkansas              49.868421  1.147079
California            49.830508  1.301889
Colorado              49.846154  1.240347
Connecticut           48.888889  3.333333
Delaware              47.500000  5.000000
District of Columbia  45.000000  7.071068
Florida               49.852941  1.212678
Georgia               49.937500  0.790569
Hawaii                48.333333  4.082483
Idaho                 49.777778  1.490712
Illinois              49.902913  0.985329
Indiana               49.892473  1.036952
Iowa                  49.900000  1.000000
Kansas                49.905660  0.971286
Kentucky              49.917355  0.909091
Louisiana             49.846154  1.240347
Maine                 49.411765  2.425356
Maryland              49.600000  2.000000
Massachusetts         49.333333  2.581989
Michigan              49.880952  1.091089
Minnesota             49.886364  1.066004
Mississippi           49.879518  1.097643
Missouri              49.913793  0.928477
Montana               49.824561  1.324532
Nebraska              49.893617  1.031421
Nevada                49.444444  2.357023
New Hampshire         49.090909  3.015113
New Jersey            49.545455  2.132007
New Mexico            49.705882  1.714986
New York              49.841270  1.259882
North Carolina        49.900990  0.995037
North Dakota          49.814815  1.360828
Ohio                  49.887640  1.059998
Oklahoma              49.871795  1.132277
Oregon                49.729730  1.643990
Pennsylvania          49.852941  1.212678
Rhode Island          48.333333  4.082483
South Carolina        49.787234  1.458650
South Dakota          49.850746  1.221694
Tennessee             49.895833  1.020621
Texas                 49.960784  0.626224
Utah                  49.666667  1.825742
Vermont               49.333333  2.581989
Virginia              49.925373  0.863868
Washington            49.750000  1.581139
West Virginia         49.821429  1.336306
Wisconsin             49.863014  1.170411
Wyoming               49.583333  2.041241

In [16]:
df.groupby("STNAME").agg({"SUMLEV":np.nanmean, "CENSUS2010POP":np.nanmean})

                         SUMLEV  CENSUS2010POP
STNAME
Alabama               49.852941   1.405805e+05
Alaska                49.666667   4.734873e+04
Arizona               49.375000   7.990021e+05
Arkansas              49.868421   7.673468e+04
California            49.830508   1.262846e+06
Colorado              49.846154   1.547445e+05
Connecticut           48.888889   7.942438e+05
Delaware              47.500000   4.489670e+05
District of Columbia  45.000000   6.017230e+05
Florida               49.852941   5.529797e+05
Georgia               49.937500   1.210957e+05
Hawaii                48.333333   4.534337e+05
Idaho                 49.777778   6.967031e+04
Illinois              49.902913   2.491385e+05
Indiana               49.892473   1.394366e+05
Iowa                  49.900000   6.092710e+04
Kansas                49.905660   5.383242e+04
Kentucky              49.917355   7.172507e+04
Louisiana             49.846154   1.394884e+05
Maine                 49.411765   1.562778e+05
Maryland              49.600000   4.618842e+05
Massachusetts         49.333333   8.730172e+05
Michigan              49.880952   2.353248e+05
Minnesota             49.886364   1.205438e+05
Mississippi           49.879518   7.150113e+04
Missouri              49.913793   1.032574e+05
Montana               49.824561   3.471632e+04
Nebraska              49.893617   3.885832e+04
Nevada                49.444444   3.000612e+05
New Hampshire         49.090909   2.393582e+05
New Jersey            49.545455   7.992631e+05
New Mexico            49.705882   1.211282e+05
New York              49.841270   6.151778e+05
North Carolina        49.900990   1.888214e+05
North Dakota          49.814815   2.491078e+04
Ohio                  49.887640   2.592473e+05
Oklahoma              49.871795   9.618849e+04
Oregon                49.729730   2.070851e+05
Pennsylvania          49.852941   3.735994e+05
Rhode Island          48.333333   3.508557e+05
South Carolina        49.787234   1.968240e+05
South Dakota          49.850746   2.430388e+04
Tennessee             49.895833   1.322105e+05
Texas                 49.960784   1.972201e+05
Utah                  49.666667   1.842590e+05
Vermont               49.333333   8.343213e+04
Virginia              49.925373   1.193718e+05
Washington            49.750000   3.362270e+05
West Virginia         49.821429   6.617836e+04
Wisconsin             49.863014   1.558078e+05
Wyoming               49.583333   4.696883e+04

In [17]:
# First we're doing
# a group by on the dataframe object by the column "STNAME". This creates a new GroupBy object.
# Then we are invoking the agg() function on that object. The agg function is going to apply one or more
# functions we specify to the group dataframes and return a single row per dataframe/group. When we called
# this function we sent it two dictionary entries, each with the key indicating which column we wanted
# functions applied to. For the first column we actually supplied a tuple of two functions. Note that these
# are not function invocations, like np.nanmean(), or function names, like "nanmean" they are references to
# functions which will return single values. The groupby object will recognize the tuple and call each
# function in order on the same column. The results will be in a heirarchical index, but since they are
# columns they don't show as an index per se. Then we indicated another column and a single function we wanted
# to run.

## Transformation

In [18]:
# Transformation is different from aggregation. Where agg() returns a single value per column, so one row per
# group, tranform() returns an object that is the same size as the group. Essentially, it broadcasts the
# function you supply over the grouped dataframe, returning a new dataframe. This makes combining data later
# easy.

In [19]:
cols = ['STNAME', 'SUMLEV']
transform_df = df[cols].groupby('STNAME').transform(np.nanmean)
# to calculate difference between mean and original value
transform_df['mean_diff'] = np.absolute(transform_df['SUMLEV'] - df['SUMLEV'])
transform_df

         SUMLEV  mean_diff
0     49.852941   9.852941
1     49.852941   0.147059
2     49.852941   0.147059
3     49.852941   0.147059
4     49.852941   0.147059
...         ...        ...
3188  49.583333   0.416667
3189  49.583333   0.416667
3190  49.583333   0.416667
3191  49.583333   0.416667
3192  49.583333   0.416667

[3193 rows x 2 columns]

In [20]:
transform_df.rename({'SUMLEV':'mean_SUMLEV'}, axis = 'columns', inplace = True)
df = df.merge(transform_df, left_index = True, right_index = True)
df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015,mean_SUMLEV,mean_diff
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594,49.852941,9.852941
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333,49.852941,0.147059
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499,49.852941,0.147059
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299,49.852941,0.147059
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861,49.852941,0.147059

## Filtering

In [21]:
# The GroupBy object has build in support for filtering groups as well. It's often that you'll want to group
# by some feature, then make some transformation to the groups, then drop certain groups as part of your
# cleaning routines. The filter() function takes in a function which it applies to each group dataframe and
# returns either a True or a False, depending upon whether that group should be included in the results.

In [22]:
df.groupby('STNAME').filter(lambda x: np.nanmean(x['SUMLEV'])>49.80)

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015,mean_SUMLEV,mean_diff
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594,49.852941,9.852941
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333,49.852941,0.147059
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499,49.852941,0.147059
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299,49.852941,0.147059
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861,49.852941,0.147059
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3164,50,2,3,55,133,Wisconsin,Waukesha County,389891,389938,390076,...,0.038132,0.760109,-0.719858,0.102448,3.180527,1.189727,2.077633,0.593567,49.863014,0.136986
3165,50,2,3,55,135,Wisconsin,Waupaca County,52410,52410,52422,...,6.292687,-0.441031,-0.480617,3.359933,-2.011937,6.561277,-0.134227,-0.173022,49.863014,0.136986
3166,50,2,3,55,137,Wisconsin,Waushara County,24496,24496,24506,...,-4.097017,-4.906711,-4.397793,5.174486,-2.160399,-3.810226,-4.535615,-4.024395,49.863014,0.136986
3167,50,2,3,55,139,Wisconsin,Winnebago County,166994,166994,167059,...,0.833819,-2.406192,-4.557985,0.842573,3.502335,1.531624,-1.545153,-3.685304,49.863014,0.136986
3168,50,2,3,55,141,Wisconsin,Wood County,74749,74749,74807,...,-6.901200,-5.596471,-3.958322,-3.733590,-4.562809,-6.442917,-5.040889,-3.414223,49.863014,0.136986

## Applying

In [23]:
# By far the most common operation I invoke on groupby objects is the apply() function. This allows you to
# apply an arbitrary function to each group, and stitch the results back for each apply() into a single
# dataframe where the index is preserved.

In [24]:
df = pd.read_csv('census.csv')
df = df[['STNAME', 'SUMLEV']]
df.head()

    STNAME  SUMLEV
0  Alabama      40
1  Alabama      50
2  Alabama      50
3  Alabama      50
4  Alabama      50

In [25]:
def calc_mean_diff(group):
    # group is a dataframe just of whatever we have grouped by, e.g. STNAME, so we can treat
    # this as the complete dataframe
    avg = np.nanmean(group['SUMLEV'])
    group['mean_diff'] = np.absolute(avg - group['SUMLEV'])
    return group

df.groupby('STNAME').apply(calc_mean_diff).head()

    STNAME  SUMLEV  mean_diff
0  Alabama      40   9.852941
1  Alabama      50   0.147059
2  Alabama      50   0.147059
3  Alabama      50   0.147059
4  Alabama      50   0.147059

Groupby is a powerful and commonly used tool for data cleaning and data analysis. Once you have grouped the data by some category you have a dataframe of just those values and you can conduct aggregated analsyis on the segments that you are interested. The groupby() function follows a split-apply-combine approach - first the data is split into subgroups, then you can apply some transformation, filtering, or aggregation, then the results are combined automatically by pandas for us.